import { PackagingTemplate, MaterialOption } from "@/types/packaging";

export const TEMPLATES: PackagingTemplate[] = [
  {
    id: "reverse-tuck",
    name: "Boîte Pliante - Pattes Opposées",
    code: "ECMA A20.20.03.01",
    category: "Étuis Pliants",
    description: "Modèle standard pour cosmétiques, pharmacie et petits flacons. Fermeture haute et basse inversée.",
    defaultDimensions: {
      length: 80,
      width: 50,
      height: 140,
      caliper: 0.45,
      glueFlap: 15,
      bleed: 3,
      safetyMargin: 4,
      tuckFlap: 18,
    },
  },
  {
    id: "mailer-box",
    name: "Boîte Postale E-commerce",
    code: "FEFCO 0427",
    category: "Expédition & Mailer",
    description: "Boîte d'expédition avec rabats latéraux anti-poussière et fermeture frontale verrouillable.",
    defaultDimensions: {
      length: 220,
      width: 160,
      height: 70,
      caliper: 1.5,
      glueFlap: 0,
      bleed: 3,
      safetyMargin: 5,
      tuckFlap: 25,
    },
  },
  {
    id: "sleeve-tray",
    name: "Fourreau & Tiroir Coulissant",
    code: "ECMA B10.00.00",
    category: "Coffrets Premium",
    description: "Système coulissant deux pièces avec fourreau ouvert aux extrémités et barquette intérieure.",
    defaultDimensions: {
      length: 150,
      width: 100,
      height: 40,
      caliper: 0.5,
      glueFlap: 14,
      bleed: 3,
      safetyMargin: 3,
      tuckFlap: 0,
    },
  },
  {
    id: "crash-lock",
    name: "Boîte Fond Automatique",
    code: "ECMA A55.20.01",
    category: "Montage Rapide",
    description: "Fond se déployant instantanément à l'ouverture pour cadence de conditionnement élevée.",
    defaultDimensions: {
      length: 100,
      width: 70,
      height: 180,
      caliper: 0.45,
      glueFlap: 16,
      bleed: 3,
      safetyMargin: 4,
      tuckFlap: 20,
    },
  },
];

export const MATERIALS: MaterialOption[] = [
  {
    id: "sbs-350",
    name: "Carton Plat SBS 1 Face Blanchie",
    family: "Carton Compact",
    grammage: 350,
    caliperMm: 0.45,
    color: "#F8FAFC",
    texture: "smooth",
    foldLossFactor: 1.0,
  },
  {
    id: "kraft-brown-300",
    name: "Kraft Naturel Recyclé Brun",
    family: "Écologique / Kraft",
    grammage: 300,
    caliperMm: 0.42,
    color: "#C8A165",
    texture: "kraft",
    foldLossFactor: 0.95,
  },
  {
    id: "corrugated-e-flute",
    name: "Carton Ondulé Micro-cannelure E",
    family: "Ondulé",
    grammage: 420,
    caliperMm: 1.5,
    color: "#D2B48C",
    texture: "corrugated",
    foldLossFactor: 1.4,
  },
  {
    id: "sbs-premium-black",
    name: "Carton Teinté Masse Noir Ébène",
    family: "Luxe & Cosmétique",
    grammage: 380,
    caliperMm: 0.5,
    color: "#1E2229",
    texture: "matte",
    foldLossFactor: 1.05,
  },
];
