/**
 * PI-1P — initial knowledge base: high-value product archetypes, each reasoned as a packaging designer
 * would (what the product is, how it behaves, how it is used and bought, what the pack must do).
 *
 * Internal editorial rules (PI1_ARCHETYPE_SOURCE, confidence "medium"): tendencies, not facts about one
 * brand. Regulatory requirements (tamper evidence, child resistance) stay "unknown": no obligation is
 * invented. No engine structure id appears here; the packaging resolver maps families to structures.
 */
import { PI1_ARCHETYPE_SOURCE } from "./provenance";
import type { PackagingRequirements, ProductArchetype, ProductIntelligence } from "./types";
import { PACKAGING_REQUIREMENT_KEYS } from "./vocabulary";

type Req = Partial<Record<keyof PackagingRequirements, "required" | "preferred" | "notRelevant">>;
type Fields = Omit<ProductIntelligence, "confidence" | "origin" | "provenance" | "packagingRequirements">;

/** Every requirement not stated is "unknown" (never a silent default). */
const req = (r: Req): PackagingRequirements =>
  Object.fromEntries(PACKAGING_REQUIREMENT_KEYS.map((k) => [k, r[k] ?? "unknown"])) as PackagingRequirements;

const arch = (id: string, fr: string, en: string, terms: string[], rationale: string, r: Req, f: Fields, catalogueProducts?: string[]): ProductArchetype => ({
  id, label: { fr, en }, terms, rationale, ...(catalogueProducts ? { catalogueProducts } : {}),
  intelligence: { ...f, packagingRequirements: req(r), confidence: "medium", origin: "ruleBased", provenance: [PI1_ARCHETYPE_SOURCE] },
});

const RAW: ProductArchetype[] = [
  // ── Beverages ──────────────────────────────────────────────────────────────
  arch("bottledWater", "Eau en bouteille", "Bottled water", ["eau minerale", "eau de source", "eau plate", "eau gazeuse", "eau petillante","bottled water", "mineral water"],
    "Liquide pur, très concurrentiel, acheté en volume : étanchéité et transport priment ; la transparence montre la pureté.",
    { needsLeakProtection: "required", needsResealability: "required", needsTransparency: "preferred", needsPortability: "preferred", needsStackability: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "beverages", productSubcategory: "water", physicalState: "liquid", viscosity: "none", flowBehavior: "pourable", sensitivities: ["contamination", "leakage"],
      fragility: "low", temperatureSensitivity: "low", usageFrequency: "multipleDaily", usageContext: ["home", "office", "travel", "gym", "outdoor"], portionModel: "singleServe",
      dispensingNeed: ["screwCap", "pour"], portability: "high", targetAudience: ["massMarket", "family"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"],
      competitionLevel: "saturated", shelfImportance: "high", preferredPackagingFamilies: ["bottle", "sachet", "can", "carton"], preferredMaterials: ["PET", "glass", "aluminum"],
      positioningTerritories: ["natural", "minimalist", "accessible"],
      designSignals: { colorDirection: { primary: ["blanc", "bleus clairs"], avoid: ["aplats sombres couvrants"], reason: "pureté et fraîcheur ; laisser voir le produit" } } },
    ["Eau de source"]),

  arch("fruitJuice", "Jus de fruits", "Fruit juice", ["jus de fruit", "jus", "nectar", "smoothie", "fruit juice", "juice"],
    "Liquide sensible à l'oxydation et à la chaleur, souvent réfrigéré : barrière et refermeture ; la couleur du fruit vend.",
    { needsLeakProtection: "required", needsResealability: "required", needsBarrierProtection: "preferred", needsLightProtection: "preferred", needsShelfImpact: "required", needsVisibility: "preferred" },
    { productCategory: "beverages", productSubcategory: "juice", physicalState: "liquid", viscosity: "low", flowBehavior: "pourable", sensitivities: ["oxygen", "heat", "light", "contamination", "leakage"],
      fragility: "low", temperatureSensitivity: "high", usageFrequency: "daily", usageContext: ["home", "travel", "restaurant"], portionModel: "unknown", dispensingNeed: ["pour", "screwCap"],
      portability: "medium", targetAudience: ["family", "massMarket", "healthConsumers"], pricePosition: "mid", purchaseContext: ["supermarket", "convenience", "restaurant"],
      competitionLevel: "high", shelfImportance: "critical", preferredPackagingFamilies: ["bottle", "carton", "can", "pouch"], preferredMaterials: ["PET", "glass", "carton"],
      positioningTerritories: ["natural", "energetic", "accessible"],
      designSignals: {
        colorDirection: { primary: ["couleur du fruit"], secondary: ["vert feuille"], reason: "le fruit est identifié en moins de 3 s" },
        photographyDirection: { primary: ["fruit frais, gouttes"], avoid: ["fruits non contenus dans la recette"], reason: "ne montrer que les ingrédients réels" },
      } },
    ["Jus pressé"]),

  arch("localBeverage", "Boisson locale (bissap, gingembre, foléré, baobab)", "Local beverage", ["bissap", "folere", "hibiscus", "gingembre", "baobab", "zobo", "tamarin"],
    "Boisson de fleurs, racines ou fruits locaux, souvent artisanale, vendue fraîche ou à température ambiante : étanchéité, conservation, couleur du produit visible ; identité d'origine forte sans folklore.",
    { needsLeakProtection: "required", needsResealability: "required", needsVisibility: "preferred", needsLightProtection: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "beverages", productSubcategory: "juice", productType: "boisson locale (fleurs, racines, fruits)", physicalState: "liquid", viscosity: "low", flowBehavior: "pourable",
      sensitivities: ["heat", "contamination", "oxygen", "light", "leakage"], fragility: "low", temperatureSensitivity: "high", usageFrequency: "daily", usageContext: ["home", "restaurant", "outdoor"],
      portionModel: "unknown", dispensingNeed: ["pour", "screwCap"], portability: "medium", targetAudience: ["massMarket", "culturallyFocused", "family"], pricePosition: "value",
      purchaseContext: ["convenience", "supermarket", "directToConsumer", "restaurant"], competitionLevel: "medium", shelfImportance: "high",
      marketRegion: ["WestAfrica", "CentralAfrica"], preferredPackagingFamilies: ["bottle", "sachet", "pouch"], preferredMaterials: ["PET", "glass"],
      positioningTerritories: ["natural", "cultural", "accessible"] },
    ["Jus de bissap", "Jus de gingembre"]),

  arch("softDrink", "Boisson gazeuse", "Soft drink", ["soda", "limonade", "boisson gazeuse", "soft drink"],
    "Liquide gazeux sous pression : contenant résistant et étanche ; achat d'impulsion, rayon saturé.",
    { needsLeakProtection: "required", needsBarrierProtection: "required", needsShelfImpact: "required", needsPortability: "preferred" },
    { productCategory: "beverages", productSubcategory: "softDrink", physicalState: "liquid", viscosity: "none", flowBehavior: "pourable", sensitivities: ["leakage", "heat"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "outdoor", "restaurant", "travel"], portionModel: "singleServe",
      dispensingNeed: ["screwCap", "pour"], portability: "high", targetAudience: ["massMarket"], pricePosition: "value",
      purchaseContext: ["convenience", "supermarket", "restaurant"], competitionLevel: "saturated", shelfImportance: "critical",
      preferredPackagingFamilies: ["can", "bottle"], preferredMaterials: ["aluminum", "PET", "glass"], positioningTerritories: ["bold", "energetic", "playful", "youthful"] }),

  arch("energyDrink", "Boisson énergisante", "Energy drink", ["boisson energisante", "energy drink", "energisant"],
    "Achat d'impulsion très concurrentiel, consommé en mobilité : canette fine, impact maximal en rayon froid.",
    { needsLeakProtection: "required", needsBarrierProtection: "required", needsShelfImpact: "required", needsPortability: "required" },
    { productCategory: "beverages", productSubcategory: "energyDrink", physicalState: "liquid", viscosity: "none", flowBehavior: "pourable", sensitivities: ["leakage", "light"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "occasional", usageContext: ["gym", "outdoor", "travel", "office"], portionModel: "singleServe",
      dispensingNeed: ["none"], portability: "high", targetAudience: ["athletes", "massMarket"], pricePosition: "mid", purchaseContext: ["convenience", "supermarket"],
      competitionLevel: "saturated", shelfImportance: "critical", preferredPackagingFamilies: ["can", "bottle"], preferredMaterials: ["aluminum", "PET"],
      positioningTerritories: ["bold", "energetic", "youthful", "technical"],
      designSignals: { colorDirection: { primary: ["couleurs saturées sur fond sombre"], reason: "contraste maximal en meuble froid" }, typographyDirection: { primary: ["sans-serif condensée, grasse"], reason: "énergie, lecture verticale sur canette fine" } } },
    ["Boisson énergisante"]),

  arch("wine", "Vin", "Wine", ["vin rouge", "vin blanc", "vin rose", "vin", "wine"],
    "Liquide sensible à la lumière et à l'oxygène, acheté sur l'étiquette : verre teinté, codes d'appellation, présentation soignée.",
    { needsLeakProtection: "required", needsLightProtection: "preferred", needsBarrierProtection: "required", needsPremiumPresentation: "preferred", needsShelfImpact: "required", needsShippingProtection: "preferred" },
    { productCategory: "beverages", productSubcategory: "wine", physicalState: "liquid", viscosity: "none", flowBehavior: "pourable", sensitivities: ["light", "oxygen", "heat", "impact"],
      fragility: "high", temperatureSensitivity: "medium", usageFrequency: "occasional", usageContext: ["home", "restaurant", "hospitality"], portionModel: "multiServe",
      dispensingNeed: ["pour"], portability: "low", targetAudience: ["middleMarket", "premium"], pricePosition: "unknown", purchaseContext: ["supermarket", "specialtyStore", "restaurant", "hotel"],
      competitionLevel: "saturated", shelfImportance: "critical", preferredPackagingFamilies: ["bottle", "box"], preferredMaterials: ["glass", "paper"],
      positioningTerritories: ["heritage", "elegant", "traditional", "sophisticated"],
      designSignals: { typographyDirection: { primary: ["sérif classique"], secondary: ["script fine pour le domaine"], reason: "codes de la catégorie vin" }, finishDirection: { primary: ["papier texturé", "dorure discrète"] } } },
    ["Vin rouge"]),

  arch("spirit", "Spiritueux", "Spirit", ["spiritueux", "whisky", "rhum", "vodka", "gin", "liqueur", "spirit"],
    "Produit de dégustation à forte valeur, souvent offert : verre lourd, présentation premium, étui de protection.",
    { needsLeakProtection: "required", needsPremiumPresentation: "required", needsShelfImpact: "required", needsShippingProtection: "preferred" },
    { productCategory: "beverages", productSubcategory: "spirit", physicalState: "liquid", viscosity: "none", flowBehavior: "pourable", sensitivities: ["impact", "light"],
      fragility: "high", temperatureSensitivity: "low", usageFrequency: "occasional", usageContext: ["home", "hospitality", "restaurant"], portionModel: "multiServe",
      dispensingNeed: ["pour"], portability: "low", targetAudience: ["premium"], pricePosition: "premium", purchaseContext: ["specialtyStore", "supermarket", "hotel"],
      competitionLevel: "high", shelfImportance: "critical", preferredPackagingFamilies: ["bottle", "box"], preferredMaterials: ["glass", "carton"],
      positioningTerritories: ["premium", "heritage", "sophisticated", "bold"] },
    ["Gin distillé"]),

  arch("beer", "Bière", "Beer", ["biere", "beer", "ipa", "lager"],
    "Liquide gazeux sensible à la lumière : canette ou verre brun ; rayon très concurrentiel, achat en lot.",
    { needsLeakProtection: "required", needsLightProtection: "required", needsBarrierProtection: "required", needsShelfImpact: "required", needsStackability: "preferred" },
    { productCategory: "beverages", productSubcategory: "beer", physicalState: "liquid", viscosity: "none", flowBehavior: "pourable", sensitivities: ["light", "oxygen", "heat", "leakage"],
      fragility: "medium", temperatureSensitivity: "high", usageFrequency: "occasional", usageContext: ["home", "restaurant", "hospitality", "outdoor"], portionModel: "singleServe",
      dispensingNeed: ["none"], portability: "medium", targetAudience: ["massMarket"], pricePosition: "mid", purchaseContext: ["supermarket", "convenience", "restaurant"],
      competitionLevel: "saturated", shelfImportance: "critical", preferredPackagingFamilies: ["can", "bottle"], preferredMaterials: ["aluminum", "glass"],
      positioningTerritories: ["bold", "artisanal", "heritage"] },
    ["Bière artisanale IPA"]),

  arch("milk", "Lait liquide", "Milk", ["lait entier", "lait demi-ecreme", "lait frais", "lait", "milk"],
    "Liquide périssable, sensible à la lumière et à la chaleur : brique opaque ou bouteille, refermeture, lisibilité familiale.",
    { needsLeakProtection: "required", needsLightProtection: "required", needsBarrierProtection: "required", needsResealability: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "beverages", productSubcategory: "milk", physicalState: "liquid", viscosity: "low", flowBehavior: "pourable", sensitivities: ["light", "heat", "contamination", "oxygen"],
      fragility: "low", temperatureSensitivity: "high", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["pour", "screwCap"],
      portability: "low", targetAudience: ["family", "massMarket", "children"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["carton", "bottle", "pouch"], preferredMaterials: ["carton", "HDPE", "PET"],
      positioningTerritories: ["natural", "accessible", "neutral"] },
    ["Lait entier"]),

  // ── Food ───────────────────────────────────────────────────────────────────
  arch("yogurt", "Yaourt", "Yogurt", ["yaourt", "yogourt", "yogurt", "lait caille", "kossam"],
    "Produit frais semi-solide, à la cuillère, en portion : pot scellé, chaîne du froid.",
    { needsBarrierProtection: "required", needsLeakProtection: "required", needsPortionControl: "preferred", needsStackability: "required", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "dairy", physicalState: "semiSolid", viscosity: "medium", flowBehavior: "scoopable", sensitivities: ["heat", "contamination", "oxygen"],
      fragility: "medium", temperatureSensitivity: "high", usageFrequency: "daily", usageContext: ["home", "office"], portionModel: "singleServe", dispensingNeed: ["spoon"],
      portability: "medium", targetAudience: ["family", "children"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["cup", "bottle", "tub"], preferredMaterials: ["PP", "PET"],
      positioningTerritories: ["natural", "accessible", "playful"] }),

  arch("milkPowder", "Lait en poudre", "Milk powder", ["lait en poudre", "milk powder", "powdered milk"],
    "Poudre hygroscopique utilisée par cuillerées pendant des semaines : barrière à l'humidité, refermeture fiable, mesurette ; achat familial de confiance.",
    { needsMoistureProtection: "required", needsBarrierProtection: "required", needsResealability: "required", needsLightProtection: "preferred", needsDispensing: "preferred", needsShelfImpact: "required", needsPortionControl: "preferred" },
    { productCategory: "food", productSubcategory: "dairy", productType: "lait en poudre", physicalState: "powder", viscosity: "none", flowBehavior: "scoopable",
      sensitivities: ["moisture", "oxygen", "contamination", "light"], fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"],
      portionModel: "multiServe", dispensingNeed: ["scoop"], portability: "low", targetAudience: ["family", "children"], pricePosition: "mid",
      purchaseContext: ["supermarket", "convenience", "pharmacy"], competitionLevel: "high", shelfImportance: "high",
      preferredPackagingFamilies: ["tin", "tub", "pouch", "sachet"], preferredMaterials: ["steel", "metallizedFilm", "composite"],
      positioningTerritories: ["accessible", "natural", "clinical"],
      designSignals: { colorDirection: { primary: ["blanc", "bleu"], reason: "pureté et confiance" }, imageryDirection: { avoid: ["allégations de santé non fournies"], reason: "aucune allégation inventée" } } }),

  arch("coffee", "Café", "Coffee", ["cafe en grains", "cafe moulu", "cafe", "coffee", "espresso", "arabica", "robusta"],
    "Grains ou mouture qui perdent leurs arômes à l'air et à la lumière : barrière, valve, refermeture ; l'origine raconte le produit.",
    { needsBarrierProtection: "required", needsLightProtection: "required", needsMoistureProtection: "required", needsResealability: "preferred", needsShelfImpact: "required" },
    { productCategory: "food", productSubcategory: "coffee", physicalState: "unknown", flowBehavior: "freeFlowing", sensitivities: ["oxygen", "light", "moisture", "oxidation"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "office", "restaurant"], portionModel: "multiServe",
      dispensingNeed: ["scoop"], portability: "low", targetAudience: ["middleMarket", "premium"], pricePosition: "mid", purchaseContext: ["supermarket", "specialtyStore", "ecommerce"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["pouch", "bag", "tin", "jar"], preferredMaterials: ["metallizedFilm", "kraft", "composite"],
      positioningTerritories: ["artisanal", "heritage", "premium"],
      designSignals: { colorDirection: { primary: ["bruns torréfiés", "crème"], secondary: ["cuivre"], reason: "codes de la torréfaction" }, materialDirection: { primary: ["kraft"], reason: "artisanal" } } },
    ["Café en grains"]),

  arch("tea", "Thé et infusions", "Tea", ["the vert", "the noir", "infusion", "tisane", "matcha", "rooibos", "tea"],
    "Feuilles sèches aromatiques sensibles à l'humidité et à la lumière, souvent en sachets-doses : étui ou boîte métal.",
    { needsMoistureProtection: "required", needsLightProtection: "preferred", needsBarrierProtection: "preferred", needsPortionControl: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "tea", physicalState: "solid", flowBehavior: "freeFlowing", sensitivities: ["moisture", "light", "oxygen"], fragility: "low",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "office", "hospitality"], portionModel: "singleServe", dispensingNeed: ["none"],
      portability: "medium", targetAudience: ["middleMarket", "healthConsumers"], pricePosition: "mid", purchaseContext: ["supermarket", "specialtyStore"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["box", "tin", "pouch", "sachet"], preferredMaterials: ["carton", "steel", "kraft"],
      positioningTerritories: ["natural", "elegant", "heritage"],
      designSignals: { illustrationDirection: { primary: ["botanique"], reason: "codes de l'herboristerie" } } },
    ["Thé vert"]),

  arch("flour", "Farine", "Flour", ["farine de ble", "farine de manioc", "farine de mais", "farine", "flour"],
    "Poudre de base achetée en volume : protection contre l'humidité et les nuisibles, lisibilité maximale, prix serré.",
    { needsMoistureProtection: "required", needsStackability: "preferred", needsResealability: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "flour", physicalState: "powder", viscosity: "none", flowBehavior: "freeFlowing", sensitivities: ["moisture", "contamination"],
      fragility: "low", temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "professional"], portionModel: "bulk", dispensingNeed: ["scoop", "pour"],
      portability: "low", targetAudience: ["massMarket", "family", "budget"], pricePosition: "value", purchaseContext: ["supermarket", "convenience", "professionalDistribution"],
      competitionLevel: "high", shelfImportance: "medium", preferredPackagingFamilies: ["bag", "pouch", "box"], preferredMaterials: ["paper", "kraft", "flexibleFilm"],
      positioningTerritories: ["accessible", "traditional", "neutral"] }),

  arch("cereal", "Céréales du petit-déjeuner", "Breakfast cereal", ["cereales", "cereale", "granola", "muesli", "corn flakes", "cereal"],
    "Produit sec et cassant, consommé en famille : sachet intérieur barrière + étui grand format qui sert d'affiche en rayon.",
    { needsMoistureProtection: "required", needsResealability: "preferred", needsShelfImpact: "required", needsStackability: "preferred" },
    { productCategory: "food", productSubcategory: "cereals", physicalState: "solid", flowBehavior: "freeFlowing", sensitivities: ["moisture", "impact", "oxygen"], fragility: "medium",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["pour"], portability: "low",
      targetAudience: ["family", "children", "healthConsumers"], pricePosition: "mid", purchaseContext: ["supermarket"], competitionLevel: "saturated", shelfImportance: "critical",
      preferredPackagingFamilies: ["box", "pouch", "bag"], preferredMaterials: ["carton", "flexibleFilm"], positioningTerritories: ["playful", "natural", "energetic"] },
    ["Granola croustillant"]),

  arch("spices", "Épices", "Spices", ["epices", "epice", "poivre", "penja", "curcuma", "njansang", "mbongo", "cannelle", "spices"],
    "Petites doses très aromatiques, sensibles à la lumière et à l'humidité : pot ou sachet refermable ; l'origine compte.",
    { needsMoistureProtection: "required", needsLightProtection: "preferred", needsBarrierProtection: "preferred", needsResealability: "required", needsDispensing: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "spices", physicalState: "unknown", flowBehavior: "freeFlowing", sensitivities: ["moisture", "light", "oxidation"], fragility: "low",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "restaurant", "professional"], portionModel: "multiServe", dispensingNeed: ["spoon", "other"],
      portability: "low", targetAudience: ["middleMarket", "culturallyFocused"], pricePosition: "mid", purchaseContext: ["supermarket", "specialtyStore"],
      competitionLevel: "medium", shelfImportance: "medium", preferredPackagingFamilies: ["jar", "sachet", "pouch", "tin"], preferredMaterials: ["glass", "kraft", "metallizedFilm"],
      positioningTerritories: ["artisanal", "heritage", "cultural"] },
    ["Poivre blanc de Penja"]),

  arch("sauce", "Sauce", "Sauce", ["sauce tomate", "ketchup", "mayonnaise", "moutarde", "sauce", "condiment"],
    "Liquide visqueux dosé à chaque repas : flacon souple ou verre, refermeture, dosage.",
    { needsLeakProtection: "required", needsResealability: "required", needsDispensing: "preferred", needsBarrierProtection: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "sauces", physicalState: "viscous", viscosity: "high", flowBehavior: "squeezable", sensitivities: ["oxygen", "contamination", "heat"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "restaurant"], portionModel: "multiServe",
      dispensingNeed: ["squeeze", "flipCap", "pour"], portability: "low", targetAudience: ["family", "massMarket"], pricePosition: "value", purchaseContext: ["supermarket", "convenience", "restaurant"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["bottle", "jar", "sachet", "pouch"], preferredMaterials: ["PET", "glass", "PP"],
      positioningTerritories: ["accessible", "bold"] }),

  arch("artisanalSauce", "Sauce artisanale pimentée", "Artisanal hot sauce", ["piment a l'huile", "sauce pimentee", "sauce piquante", "hot sauce", "piment"],
    "Petite production artisanale, huile et piment sensibles à l'oxydation : petit verre qui montre la recette, étiquette au caractère affirmé.",
    { needsLeakProtection: "required", needsResealability: "required", needsLightProtection: "preferred", needsVisibility: "preferred", needsShelfImpact: "required" },
    { productCategory: "food", productSubcategory: "sauces", productType: "sauce pimentée artisanale", physicalState: "viscous", viscosity: "medium", flowBehavior: "pourable",
      sensitivities: ["oxidation", "light", "leakage"], fragility: "medium", temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "restaurant"],
      portionModel: "multiServe", dispensingNeed: ["spoon", "pour"], portability: "low", targetAudience: ["culturallyFocused", "middleMarket"], pricePosition: "mid",
      purchaseContext: ["specialtyStore", "directToConsumer", "ecommerce"], competitionLevel: "medium", shelfImportance: "high",
      preferredPackagingFamilies: ["jar", "bottle"], preferredMaterials: ["glass"], positioningTerritories: ["artisanal", "bold", "cultural", "energetic"],
      designSignals: { colorDirection: { primary: ["rouge piment"], secondary: ["noir", "kraft"], reason: "codes énergiques des sauces pimentées" }, typographyDirection: { primary: ["typographie artisanale, tamponnée"] } } },
    ["Piment à l'huile"]),

  arch("honey", "Miel", "Honey", ["miel", "honey"],
    "Liquide très visqueux qui peut cristalliser, vendu sur sa couleur : verre qui montre le produit, fermeture étanche.",
    { needsLeakProtection: "required", needsResealability: "required", needsVisibility: "preferred", needsTransparency: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "spreads", physicalState: "viscous", viscosity: "high", flowBehavior: "spreadable", sensitivities: ["moisture", "heat"], fragility: "medium",
      temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["spoon", "squeeze"], portability: "low",
      targetAudience: ["family", "healthConsumers"], pricePosition: "mid", purchaseContext: ["supermarket", "specialtyStore", "directToConsumer"],
      competitionLevel: "medium", shelfImportance: "medium", preferredPackagingFamilies: ["jar", "bottle"], preferredMaterials: ["glass", "PET"],
      positioningTerritories: ["natural", "artisanal", "heritage"],
      designSignals: { colorDirection: { primary: ["ambre", "doré"], reason: "écho à la couleur du produit visible" } } },
    ["Miel de fleurs"]),

  arch("jam", "Confiture", "Jam", ["confiture", "gelee de fruits", "marmelade", "jam"],
    "Pâte de fruits sucrée, ouverte et refermée souvent : bocal en verre qui montre le fruit, couvercle refermable.",
    { needsResealability: "required", needsLeakProtection: "preferred", needsVisibility: "preferred", needsTransparency: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "spreads", physicalState: "gel", viscosity: "high", flowBehavior: "spreadable", sensitivities: ["contamination", "oxygen"], fragility: "medium",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "hospitality"], portionModel: "multiServe", dispensingNeed: ["spoon"], portability: "low",
      targetAudience: ["family"], pricePosition: "mid", purchaseContext: ["supermarket", "specialtyStore"], competitionLevel: "medium", shelfImportance: "medium",
      preferredPackagingFamilies: ["jar"], preferredMaterials: ["glass"], positioningTerritories: ["artisanal", "traditional", "natural"] },
    ["Confiture extra"]),

  arch("chocolate", "Chocolat", "Chocolate", ["tablette de chocolat", "chocolat", "chocolate", "cacao"],
    "Solide qui fond et absorbe les odeurs : barrière et emballage intérieur, étui ou papier ; achat plaisir.",
    { needsBarrierProtection: "preferred", needsMoistureProtection: "preferred", needsShelfImpact: "required" },
    { productCategory: "food", productSubcategory: "chocolate", physicalState: "solid", flowBehavior: "nonFlowing", sensitivities: ["heat", "moisture", "light", "impact"], fragility: "medium",
      temperatureSensitivity: "high", usageFrequency: "occasional", usageContext: ["home", "travel", "office"], portionModel: "multiServe", dispensingNeed: ["none"],
      portability: "high", targetAudience: ["massMarket", "family"], pricePosition: "mid", purchaseContext: ["supermarket", "convenience"], competitionLevel: "high",
      shelfImportance: "high", preferredPackagingFamilies: ["wrapper", "box", "pouch"], preferredMaterials: ["paper", "metallizedFilm", "carton"],
      positioningTerritories: ["accessible", "playful"] },
    ["Chocolat noir 70 %"]),

  arch("premiumChocolate", "Chocolat premium", "Premium chocolate", ["chocolat premium", "chocolat de luxe", "chocolat fin", "grand cru", "ballotin", "bonbons de chocolat", "pralines"],
    "Même fragilité thermique, mais acheté comme cadeau ou dégustation : présentation premium, protection, origine du cacao mise en avant.",
    { needsBarrierProtection: "preferred", needsMoistureProtection: "preferred", needsPremiumPresentation: "required", needsShippingProtection: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "chocolate", productType: "chocolat de dégustation", physicalState: "solid", flowBehavior: "nonFlowing",
      sensitivities: ["heat", "moisture", "impact", "light"], fragility: "high", temperatureSensitivity: "high", usageFrequency: "occasional", usageContext: ["home", "hospitality"],
      portionModel: "multiServe", dispensingNeed: ["none"], portability: "medium", targetAudience: ["premium"], pricePosition: "premium",
      purchaseContext: ["specialtyStore", "ecommerce", "hotel"], competitionLevel: "medium", shelfImportance: "medium",
      preferredPackagingFamilies: ["box", "wrapper", "tin"], preferredMaterials: ["carton", "paper"], positioningTerritories: ["premium", "elegant", "artisanal", "sophisticated"],
      designSignals: {
        colorDirection: { primary: ["bruns profonds"], secondary: ["or", "terracotta"], avoid: ["couleurs saturées"], reason: "retenue des codes premium" },
        finishDirection: { primary: ["dorure à chaud sur le logo", "papier texturé"] },
      } },
    ["Chocolat noir 70 %"]),

  arch("biscuits", "Biscuits", "Biscuits", ["biscuits", "biscuit", "cookies", "sables", "gaufrettes", "crackers"],
    "Produit sec et cassant, consommé en partage ou en portion : barrière à l'humidité, protection contre l'écrasement, impact en rayon.",
    { needsMoistureProtection: "required", needsBarrierProtection: "preferred", needsShippingProtection: "preferred", needsResealability: "preferred", needsShelfImpact: "required" },
    { productCategory: "food", productSubcategory: "bakery", physicalState: "solid", flowBehavior: "nonFlowing", sensitivities: ["moisture", "impact", "oxidation"], fragility: "high",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "office", "travel"], portionModel: "multiServe", dispensingNeed: ["none"], portability: "medium",
      targetAudience: ["family", "children", "massMarket"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"], competitionLevel: "high",
      shelfImportance: "high", preferredPackagingFamilies: ["pouch", "box", "tin", "wrapper"], preferredMaterials: ["flexibleFilm", "carton", "steel"],
      positioningTerritories: ["playful", "accessible", "traditional"] },
    ["Biscuits sablés"]),

  arch("snacks", "Snacks salés", "Savoury snacks", ["chips de plantain", "chips", "snack", "arachides grillees", "cacahuetes", "popcorn"],
    "Produit sec, gras et cassant : film barrière à l'oxygène et à l'humidité, souvent sous atmosphère ; achat d'impulsion.",
    { needsBarrierProtection: "required", needsMoistureProtection: "required", needsLightProtection: "preferred", needsShelfImpact: "required", needsPortability: "preferred" },
    { productCategory: "food", productSubcategory: "snacks", physicalState: "solid", flowBehavior: "nonFlowing", sensitivities: ["oxygen", "moisture", "light", "impact", "oxidation"],
      fragility: "high", temperatureSensitivity: "low", usageFrequency: "occasional", usageContext: ["home", "travel", "outdoor", "office"], portionModel: "unknown",
      dispensingNeed: ["none"], portability: "high", targetAudience: ["massMarket", "children", "family"], pricePosition: "value", purchaseContext: ["convenience", "supermarket"],
      competitionLevel: "saturated", shelfImportance: "critical", preferredPackagingFamilies: ["bag", "pouch", "can"], preferredMaterials: ["metallizedFilm", "flexibleFilm"],
      positioningTerritories: ["bold", "playful", "energetic"],
      designSignals: { colorDirection: { primary: ["couleurs saturées et joyeuses"], reason: "visibilité en supérette" }, photographyDirection: { primary: ["produit appétissant en gros plan"] } } },
    ["Chips croustillantes", "Chips de plantain"]),

  arch("edibleOil", "Huile alimentaire", "Edible oil", ["huile de palme", "huile d'arachide", "huile d'olive", "huile vegetale", "huile de cuisson", "huile de tournesol", "cooking oil"],
    "Liquide gras qui s'oxyde à la lumière : bouteille étanche, souvent opaque ou teintée ; produit de base, lisibilité.",
    { needsLeakProtection: "required", needsLightProtection: "preferred", needsResealability: "required", needsDispensing: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "edibleOils", physicalState: "liquid", viscosity: "medium", flowBehavior: "pourable", sensitivities: ["light", "oxidation", "heat", "leakage"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "restaurant", "professional"], portionModel: "multiServe",
      dispensingNeed: ["pour", "screwCap"], portability: "low", targetAudience: ["massMarket", "family"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"],
      competitionLevel: "high", shelfImportance: "medium", preferredPackagingFamilies: ["bottle", "tin"], preferredMaterials: ["PET", "glass", "steel"],
      positioningTerritories: ["accessible", "traditional", "natural"] },
    ["Huile de palme", "Huile d'arachide", "Huile d'olive vierge extra"]),

  arch("traditionalFood", "Produit alimentaire traditionnel (gari)", "Traditional food (gari)", ["gari", "tapioca", "couscous de manioc", "semoule de manioc", "garri"],
    "Semoule sèche de manioc, aliment de base d'Afrique de l'Ouest et centrale : protection contre l'humidité, grand format, lisibilité ; identité culturelle forte sans caricature.",
    { needsMoistureProtection: "required", needsResealability: "preferred", needsStackability: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "grains", productType: "semoule de manioc (gari)", physicalState: "granules", viscosity: "none", flowBehavior: "freeFlowing",
      sensitivities: ["moisture", "contamination"], fragility: "low", temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home"], portionModel: "bulk",
      dispensingNeed: ["scoop", "pour"], portability: "low", targetAudience: ["massMarket", "family", "culturallyFocused"], pricePosition: "value",
      purchaseContext: ["supermarket", "convenience", "directToConsumer"], competitionLevel: "medium", shelfImportance: "medium",
      marketRegion: ["WestAfrica", "CentralAfrica"], preferredPackagingFamilies: ["bag", "pouch"], preferredMaterials: ["flexibleFilm", "kraft", "paper"],
      positioningTerritories: ["traditional", "cultural", "artisanal", "accessible"],
      cultureContext: { categoryConventions: ["produit de base : grand nom lisible, mentions claires"], localVisualCodes: ["motifs textiles locaux possibles en accent, jamais en caricature"] } },
    ["Gari blanc"]),

  arch("frozenFood", "Surgelé", "Frozen food", ["surgele", "surgeles", "congele", "frozen"],
    "Produit à −18 °C qui subit condensation et manipulations : matériaux résistants au froid et à l'humidité, empilables, photo du produit cuisiné.",
    { needsMoistureProtection: "required", needsBarrierProtection: "required", needsStackability: "required", needsShelfImpact: "required" },
    { productCategory: "food", productSubcategory: "frozenFood", physicalState: "frozen", flowBehavior: "nonFlowing", sensitivities: ["heat", "moisture", "impact"], fragility: "medium",
      temperatureSensitivity: "high", usageFrequency: "occasional", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["none"], portability: "low",
      targetAudience: ["family", "massMarket"], pricePosition: "mid", purchaseContext: ["supermarket"], competitionLevel: "high", shelfImportance: "high",
      preferredPackagingFamilies: ["box", "bag", "tray", "tub"], preferredMaterials: ["carton", "flexibleFilm", "PP"], positioningTerritories: ["accessible", "modern"] }),

  arch("readyMeal", "Plat préparé", "Ready meal", ["plat prepare", "plat cuisine", "ready meal", "repas a emporter", "barquette repas"],
    "Portion individuelle réchauffée dans son contenant : barquette scellée, tenue à la chaleur, information de préparation claire.",
    { needsBarrierProtection: "required", needsLeakProtection: "required", needsPortionControl: "required", needsStackability: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "readyMeals", physicalState: "mixed", flowBehavior: "nonFlowing", sensitivities: ["heat", "contamination", "oxygen", "leakage"],
      fragility: "medium", temperatureSensitivity: "high", usageFrequency: "occasional", usageContext: ["home", "office"], portionModel: "singleServe", dispensingNeed: ["none"],
      portability: "medium", targetAudience: ["massMarket", "middleMarket"], pricePosition: "mid", purchaseContext: ["supermarket", "convenience"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["tray", "box", "cup"], preferredMaterials: ["PP", "carton"],
      positioningTerritories: ["modern", "accessible"] }),

  arch("babyFood", "Aliment pour bébé", "Baby food", ["aliment pour bebe", "petit pot bebe", "puree bebe", "baby food", "bouillie"],
    "Aliment sensible pour un public vulnérable : hygiène et intégrité du contenant prioritaires, information parentale claire ; exigences réglementaires à sourcer.",
    { needsBarrierProtection: "required", needsLeakProtection: "required", needsPortionControl: "required", needsShelfImpact: "preferred" },
    { productCategory: "food", productSubcategory: "babyFood", physicalState: "paste", viscosity: "medium", flowBehavior: "scoopable", sensitivities: ["contamination", "oxygen", "heat"],
      fragility: "medium", temperatureSensitivity: "medium", usageFrequency: "multipleDaily", usageContext: ["home", "travel"], portionModel: "singleServe",
      dispensingNeed: ["spoon", "squeeze"], portability: "medium", targetAudience: ["family", "children"], pricePosition: "mid", purchaseContext: ["supermarket", "pharmacy"],
      competitionLevel: "medium", shelfImportance: "high", regulatoryContext: { status: "unknown" }, preferredPackagingFamilies: ["jar", "pouch", "cup"],
      preferredMaterials: ["glass", "flexibleFilm", "PP"], positioningTerritories: ["natural", "clinical", "accessible"] }),

  // ── Supplements ────────────────────────────────────────────────────────────
  arch("proteinPowder", "Protéine en poudre", "Protein powder", ["proteine en poudre", "whey", "proteine", "protein powder", "mass gainer", "caseine"],
    "Poudre en gros volume dosée à la mesurette pendant des semaines : pot large refermable, protection contre l'humidité, codes sportifs.",
    { needsMoistureProtection: "required", needsResealability: "required", needsDispensing: "required", needsPortionControl: "preferred", needsBarrierProtection: "preferred", needsShelfImpact: "required" },
    { productCategory: "supplements", productSubcategory: "proteinPowder", physicalState: "powder", viscosity: "none", flowBehavior: "scoopable", sensitivities: ["moisture", "oxygen", "heat"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["gym", "home"], portionModel: "multiServe", dispensingNeed: ["scoop"],
      portability: "low", targetAudience: ["athletes", "healthConsumers"], pricePosition: "premium", purchaseContext: ["specialtyStore", "ecommerce", "pharmacy"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["tub", "pouch", "bag"], preferredMaterials: ["HDPE", "PET", "metallizedFilm"],
      positioningTerritories: ["energetic", "technical", "bold", "scientific"],
      designSignals: { typographyDirection: { primary: ["sans-serif grasse, condensée"], reason: "performance" }, imageryDirection: { avoid: ["allégations de performance non fournies"] } } },
    ["Protéine whey"]),

  arch("vitaminSupplement", "Vitamines", "Vitamin supplement", ["vitamines", "vitamine", "multivitamines", "comprimes de vitamines", "vitamin"],
    "Comprimés ou gélules dosés quotidiennement, sensibles à l'humidité : flacon ou étui à blisters, information de dosage très lisible.",
    { needsMoistureProtection: "required", needsResealability: "required", needsPortionControl: "required", needsLightProtection: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "supplements", productSubcategory: "vitamins", physicalState: "tablet", flowBehavior: "nonFlowing", sensitivities: ["moisture", "light", "heat"], fragility: "low",
      temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "travel"], portionModel: "multiServe", dispensingNeed: ["screwCap"],
      portability: "medium", targetAudience: ["healthConsumers", "family"], pricePosition: "mid", purchaseContext: ["pharmacy", "supermarket", "ecommerce"],
      competitionLevel: "high", shelfImportance: "high", regulatoryContext: { status: "unknown" }, preferredPackagingFamilies: ["bottle", "box", "blister", "tub"],
      preferredMaterials: ["HDPE", "PET", "carton"], positioningTerritories: ["clinical", "scientific", "modern"] }),

  arch("herbalSupplement", "Complément à base de plantes", "Herbal supplement", ["complement a base de plantes", "complement naturel", "moringa", "gelules de plantes", "herbal supplement", "complement alimentaire"],
    "Plantes en gélules ou en poudre, sensibles à l'humidité : pot ou sachet refermable ; registre naturel sans promesse de santé non sourcée.",
    { needsMoistureProtection: "required", needsResealability: "required", needsLightProtection: "preferred", needsPortionControl: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "supplements", productSubcategory: "herbalSupplement", physicalState: "unknown", sensitivities: ["moisture", "light", "oxidation"], fragility: "low",
      temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["screwCap", "scoop"], portability: "medium",
      targetAudience: ["healthConsumers", "environmentallyConscious"], pricePosition: "mid", purchaseContext: ["pharmacy", "specialtyStore", "ecommerce", "directToConsumer"],
      competitionLevel: "medium", shelfImportance: "medium", regulatoryContext: { status: "unknown" }, preferredPackagingFamilies: ["jar", "bottle", "pouch", "tub"],
      preferredMaterials: ["glass", "PET", "kraft"], positioningTerritories: ["natural", "organic", "traditional"],
      designSignals: { illustrationDirection: { primary: ["botanique précise"], reason: "identifier la plante" }, imageryDirection: { avoid: ["allégations de santé inventées"] } } }),

  // ── Cosmetics / personal care ──────────────────────────────────────────────
  arch("shampoo", "Shampoing", "Shampoo", ["shampoing", "shampooing", "shampoo"],
    "Liquide visqueux utilisé sous la douche, mains mouillées : flacon souple, bouchon clapet ou pompe, étanchéité.",
    { needsLeakProtection: "required", needsDispensing: "required", needsResealability: "required", needsShelfImpact: "required" },
    { productCategory: "cosmetics", productSubcategory: "shampoo", physicalState: "viscous", viscosity: "medium", flowBehavior: "squeezable", sensitivities: ["leakage", "contamination"],
      fragility: "low", temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "hospitality", "travel"], portionModel: "multiServe",
      dispensingNeed: ["flipCap", "pump", "squeeze"], portability: "medium", targetAudience: ["beautyConsumers", "massMarket", "family"], pricePosition: "mid",
      purchaseContext: ["supermarket", "beautyStore", "pharmacy"], competitionLevel: "saturated", shelfImportance: "critical",
      preferredPackagingFamilies: ["bottle", "pump", "tube", "sachet"], preferredMaterials: ["HDPE", "PET", "PP"], positioningTerritories: ["natural", "modern", "accessible"] },
    ["Shampoing doux"]),

  arch("conditioner", "Après-shampoing", "Conditioner", ["apres-shampoing", "apres shampoing", "apres-shampooing", "conditioner", "demelant"],
    "Crème fluide utilisée en complément du shampoing : même gamme visuelle, flacon souple ou tube, distribution facile.",
    { needsLeakProtection: "required", needsDispensing: "required", needsResealability: "required", needsShelfImpact: "preferred" },
    { productCategory: "cosmetics", productSubcategory: "conditioner", physicalState: "cream", viscosity: "high", flowBehavior: "squeezable", sensitivities: ["contamination", "leakage"],
      fragility: "low", temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "hospitality"], portionModel: "multiServe", dispensingNeed: ["flipCap", "squeeze", "pump"],
      portability: "medium", targetAudience: ["beautyConsumers", "massMarket"], pricePosition: "mid", purchaseContext: ["supermarket", "beautyStore"],
      competitionLevel: "saturated", shelfImportance: "high", preferredPackagingFamilies: ["bottle", "tube", "pump"], preferredMaterials: ["HDPE", "PP", "PET"],
      positioningTerritories: ["natural", "modern", "feminine"] }),

  arch("hairCream", "Crème capillaire", "Hair cream", ["creme capillaire", "creme pour cheveux", "creme coiffante", "defrisant", "pommade capillaire", "hair cream", "beurre capillaire"],
    "Crème épaisse prélevée au doigt : pot large à vis, étanche ; rayon beauté très concurrentiel, codes capillaires afro forts.",
    { needsResealability: "required", needsLeakProtection: "preferred", needsShelfImpact: "required", needsDispensing: "notRelevant" },
    { productCategory: "cosmetics", productSubcategory: "hairCream", physicalState: "cream", viscosity: "high", flowBehavior: "scoopable", sensitivities: ["contamination", "heat", "oxidation"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "professional"], portionModel: "multiServe", dispensingNeed: ["none"],
      portability: "medium", targetAudience: ["beautyConsumers", "massMarket"], pricePosition: "mid", purchaseContext: ["beautyStore", "supermarket", "professionalDistribution"],
      competitionLevel: "saturated", shelfImportance: "critical", preferredPackagingFamilies: ["tub", "jar", "tube"], preferredMaterials: ["PP", "PET"],
      positioningTerritories: ["natural", "bold", "feminine", "cultural"],
      designSignals: { typographyDirection: { primary: ["nom de gamme très grand"], reason: "lecture à distance en rayon beauté" }, imageryDirection: { avoid: ["avant/après non fournis"] } } }),

  arch("hairOil", "Huile capillaire", "Hair oil", ["huile capillaire", "huile pour cheveux", "huile de coco", "huile de ricin", "hair oil"],
    "Liquide gras appliqué par petites quantités : flacon à bec verseur, pipette ou pompe ; étanchéité, protection de la lumière.",
    { needsLeakProtection: "required", needsDispensing: "required", needsLightProtection: "preferred", needsResealability: "required", needsShelfImpact: "preferred" },
    { productCategory: "cosmetics", productSubcategory: "hairOil", physicalState: "liquid", viscosity: "medium", flowBehavior: "pourable", sensitivities: ["light", "oxidation", "leakage"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["dropper", "pump", "flipCap"],
      portability: "medium", targetAudience: ["beautyConsumers", "culturallyFocused"], pricePosition: "mid", purchaseContext: ["beautyStore", "supermarket", "ecommerce"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["bottle", "dropper", "pump"], preferredMaterials: ["PET", "glass"],
      positioningTerritories: ["natural", "traditional", "organic"] }),

  arch("bodyLotion", "Lait corporel", "Body lotion", ["lait corporel", "lotion corporelle", "lait pour le corps", "body lotion", "lotion"],
    "Émulsion fluide appliquée en grande quantité : flacon pompe ou flip-top, contenance familiale.",
    { needsLeakProtection: "required", needsDispensing: "required", needsResealability: "required", needsShelfImpact: "required" },
    { productCategory: "cosmetics", productSubcategory: "lotion", physicalState: "cream", viscosity: "medium", flowBehavior: "pumpable", sensitivities: ["contamination", "heat"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["pump", "flipCap"],
      portability: "low", targetAudience: ["beautyConsumers", "family", "massMarket"], pricePosition: "mid", purchaseContext: ["supermarket", "beautyStore", "pharmacy"],
      competitionLevel: "saturated", shelfImportance: "high", preferredPackagingFamilies: ["pump", "bottle", "tube"], preferredMaterials: ["HDPE", "PET"],
      positioningTerritories: ["natural", "accessible", "feminine"] }),

  arch("faceCream", "Crème visage", "Face cream", ["creme visage", "creme hydratante", "creme de jour", "creme de nuit", "face cream", "beurre de karite", "karite", "creme"],
    "Crème riche, petite contenance, appliquée sur peau propre : pot ou tube, hygiène, étui pour l'information et la présentation.",
    { needsResealability: "required", needsBarrierProtection: "preferred", needsLightProtection: "preferred", needsShelfImpact: "required", needsPremiumPresentation: "preferred" },
    { productCategory: "cosmetics", productSubcategory: "faceCare", physicalState: "cream", viscosity: "high", flowBehavior: "scoopable", sensitivities: ["contamination", "oxidation", "light", "heat"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["none", "pump"],
      portability: "medium", targetAudience: ["beautyConsumers"], pricePosition: "mid", purchaseContext: ["beautyStore", "pharmacy", "supermarket"],
      competitionLevel: "saturated", shelfImportance: "high", preferredPackagingFamilies: ["jar", "tube", "pump", "box"], preferredMaterials: ["PP", "glass"],
      positioningTerritories: ["natural", "clinical", "minimalist"] },
    ["Crème hydratante", "Beurre de karité pur"]),

  arch("serum", "Sérum", "Serum", ["serum", "elixir", "huile visage", "concentre visage"],
    "Actif concentré, dosé à la goutte et sensible à la lumière : flacon pipette en verre teinté, étui, codes clean beauty.",
    { needsLightProtection: "required", needsDispensing: "required", needsLeakProtection: "required", needsBarrierProtection: "preferred", needsPremiumPresentation: "preferred", needsShelfImpact: "required" },
    { productCategory: "cosmetics", productSubcategory: "serum", physicalState: "liquid", viscosity: "low", flowBehavior: "pourable", sensitivities: ["light", "oxidation", "contamination"],
      fragility: "medium", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["dropper", "pump"],
      portability: "medium", targetAudience: ["beautyConsumers", "premium"], pricePosition: "premium", purchaseContext: ["beautyStore", "pharmacy", "ecommerce"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["dropper", "bottle", "pump", "box"], preferredMaterials: ["glass"],
      positioningTerritories: ["scientific", "minimalist", "premium", "clinical"],
      designSignals: {
        typographyDirection: { primary: ["sans-serif fine, beaucoup d'air"], reason: "précision clean beauty" },
        colorDirection: { primary: ["blanc", "neutres"], secondary: ["verre ambré"], avoid: ["surcharge décorative"] },
      } },
    ["Sérum éclat"]),

  arch("perfume", "Parfum", "Perfume", ["eau de parfum", "eau de toilette", "eau parfumee", "parfum", "fragrance", "brume parfumee", "musc"],
    "Liquide alcoolique volatil, vaporisé : flacon verre étanche, étui de présentation ; achat émotionnel ou cadeau.",
    { needsLeakProtection: "required", needsDispensing: "required", needsLightProtection: "preferred", needsPremiumPresentation: "required", needsShippingProtection: "preferred", needsShelfImpact: "required" },
    { productCategory: "cosmetics", productSubcategory: "perfume", physicalState: "liquid", viscosity: "none", flowBehavior: "sprayable", sensitivities: ["light", "heat", "oxidation", "leakage", "impact"],
      fragility: "high", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "travel"], portionModel: "multiServe", dispensingNeed: ["spray"],
      portability: "medium", targetAudience: ["beautyConsumers", "middleMarket"], pricePosition: "mid", purchaseContext: ["beautyStore", "ecommerce", "specialtyStore"],
      competitionLevel: "saturated", shelfImportance: "high", preferredPackagingFamilies: ["spray", "bottle", "box"], preferredMaterials: ["glass", "carton"],
      positioningTerritories: ["elegant", "sophisticated", "modern"] },
    ["Eau de parfum"]),

  arch("luxuryPerfume", "Parfum de luxe", "Luxury perfume", ["parfum de luxe", "parfum haut de gamme", "parfum de prestige", "luxury perfume", "extrait de parfum"],
    "Même liquide fragile, mais l'objet est le produit : flacon verre lourd, coffret rigide, finitions précieuses ; rien de superflu.",
    { needsLeakProtection: "required", needsDispensing: "required", needsLightProtection: "preferred", needsPremiumPresentation: "required", needsShippingProtection: "required", needsShelfImpact: "preferred" },
    { productCategory: "luxury", productSubcategory: "perfume", physicalState: "liquid", viscosity: "none", flowBehavior: "sprayable", sensitivities: ["light", "heat", "oxidation", "impact", "leakage"],
      fragility: "high", temperatureSensitivity: "medium", usageFrequency: "occasional", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["spray"],
      portability: "low", targetAudience: ["luxury"], pricePosition: "luxury", purchaseContext: ["specialtyStore", "beautyStore", "directToConsumer"],
      competitionLevel: "high", shelfImportance: "medium", preferredPackagingFamilies: ["spray", "bottle", "box"], preferredMaterials: ["glass", "carton"],
      positioningTerritories: ["luxury", "elegant", "sophisticated", "minimalist"],
      designSignals: {
        compositionDirection: { primary: ["un seul point focal, grand blanc tournant"], reason: "le luxe se dit par la retenue" },
        finishDirection: { primary: ["dorure à chaud", "soft touch", "gaufrage"], avoid: ["effets multiples sur la même face"] },
      } },
    ["Eau de parfum"]),

  arch("luxuryFaceCream", "Soin visage premium", "Premium skincare", ["creme de luxe", "soin de luxe", "creme premium", "soin premium", "soin haut de gamme", "anti-age premium"],
    "Crème à forte valeur, appliquée avec soin : pot verre lourd, étui rigide ou pliant premium, information INCI lisible malgré l'épure.",
    { needsResealability: "required", needsBarrierProtection: "preferred", needsLightProtection: "preferred", needsPremiumPresentation: "required", needsShelfImpact: "preferred", needsShippingProtection: "preferred" },
    { productCategory: "luxury", productSubcategory: "luxuryCosmetics", physicalState: "cream", viscosity: "high", flowBehavior: "scoopable", sensitivities: ["oxidation", "light", "contamination"],
      fragility: "medium", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["spoon", "pump"],
      portability: "low", targetAudience: ["luxury", "beautyConsumers"], pricePosition: "luxury", purchaseContext: ["beautyStore", "specialtyStore", "ecommerce"],
      competitionLevel: "high", shelfImportance: "medium", preferredPackagingFamilies: ["jar", "box", "pump"], preferredMaterials: ["glass", "carton"],
      positioningTerritories: ["luxury", "scientific", "elegant", "minimalist"] },
    ["Crème hydratante"]),

  arch("micellarWater", "Eau micellaire", "Micellar water", ["eau micellaire", "micellar water", "lotion micellaire", "demaquillant"],
    "Lotion nettoyante non buvable, appliquée sur coton matin et soir : flacon souple ou pompe, étanchéité ; codes soin, jamais ceux d'une eau de boisson.",
    { needsLeakProtection: "required", needsDispensing: "preferred", needsResealability: "required", needsShelfImpact: "required" },
    { productCategory: "cosmetics", productSubcategory: "cleanser", physicalState: "liquid", viscosity: "none", flowBehavior: "pourable", sensitivities: ["contamination", "leakage"],
      fragility: "low", temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "travel"], portionModel: "multiServe", dispensingNeed: ["flipCap", "pump"],
      portability: "medium", targetAudience: ["beautyConsumers", "massMarket"], pricePosition: "mid", purchaseContext: ["pharmacy", "beautyStore", "supermarket"],
      competitionLevel: "high", shelfImportance: "high", preferredPackagingFamilies: ["bottle", "pump"], preferredMaterials: ["PET", "HDPE"],
      positioningTerritories: ["clinical", "minimalist", "neutral"],
      designSignals: { imageryDirection: { avoid: ["verre d'eau, codes de boisson"], reason: "un cosmétique ne doit pas ressembler à une eau de boisson" } } }),

  arch("floralWater", "Eau florale", "Floral water", ["eau florale", "hydrolat", "eau de rose", "floral water"],
    "Hydrolat de distillation, souvent vaporisé sur la peau, sensible à la lumière et à la contamination : flacon spray ou bouchon, verre teinté ou PET opaque.",
    { needsLightProtection: "preferred", needsLeakProtection: "required", needsResealability: "required", needsDispensing: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "cosmetics", productSubcategory: "skincare", physicalState: "liquid", viscosity: "none", flowBehavior: "sprayable", sensitivities: ["light", "contamination", "heat"],
      fragility: "medium", temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home"], portionModel: "multiServe", dispensingNeed: ["spray", "screwCap"],
      portability: "medium", targetAudience: ["beautyConsumers", "environmentallyConscious"], pricePosition: "mid", purchaseContext: ["specialtyStore", "beautyStore", "ecommerce"],
      competitionLevel: "medium", shelfImportance: "medium", preferredPackagingFamilies: ["spray", "bottle"], preferredMaterials: ["glass", "PET"],
      positioningTerritories: ["natural", "artisanal", "elegant"] }),

  arch("barSoap", "Savon solide", "Bar soap", ["savon noir", "savon solide", "savon artisanal", "pain de savon", "savon"],
    "Solide qui doit respirer et rester sec : étui carton ou papier, souvent artisanal ; information au dos.",
    { needsMoistureProtection: "preferred", needsShelfImpact: "preferred", needsLeakProtection: "notRelevant" },
    { productCategory: "personalCare", productSubcategory: "soap", physicalState: "solid", flowBehavior: "nonFlowing", sensitivities: ["moisture"], fragility: "low",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "hospitality"], portionModel: "singleServe", dispensingNeed: ["none"], portability: "medium",
      targetAudience: ["massMarket", "environmentallyConscious"], pricePosition: "value", purchaseContext: ["supermarket", "specialtyStore", "directToConsumer"],
      competitionLevel: "high", shelfImportance: "medium", preferredPackagingFamilies: ["box", "wrapper", "sleeve"], preferredMaterials: ["kraft", "paper", "carton"],
      positioningTerritories: ["artisanal", "natural", "traditional"] },
    ["Savon saponifié à froid", "Savon noir"]),

  arch("liquidSoap", "Savon liquide", "Liquid soap", ["savon liquide", "savon pour les mains", "gel douche", "liquid soap", "hand wash"],
    "Liquide visqueux utilisé plusieurs fois par jour, mains mouillées : pompe et stabilité du flacon ; recharge possible.",
    { needsLeakProtection: "required", needsDispensing: "required", needsResealability: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "personalCare", productSubcategory: "liquidSoap", physicalState: "viscous", viscosity: "medium", flowBehavior: "pumpable", sensitivities: ["leakage", "contamination"],
      fragility: "low", temperatureSensitivity: "low", usageFrequency: "multipleDaily", usageContext: ["home", "office", "hospitality", "restaurant"], portionModel: "multiServe",
      dispensingNeed: ["pump", "flipCap"], portability: "low", targetAudience: ["family", "massMarket"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"],
      competitionLevel: "high", shelfImportance: "medium", preferredPackagingFamilies: ["pump", "bottle", "pouch"], preferredMaterials: ["PET", "HDPE", "flexibleFilm"],
      positioningTerritories: ["natural", "accessible", "modern"] }),

  arch("deodorant", "Déodorant", "Deodorant", ["deodorant", "anti-transpirant", "roll-on", "deo"],
    "Format selon le mode d'application (spray, bille, stick) : distribution intégrée, portabilité, gamme masculine ou féminine marquée.",
    { needsDispensing: "required", needsLeakProtection: "required", needsPortability: "preferred", needsShelfImpact: "required" },
    { productCategory: "personalCare", productSubcategory: "deodorant", physicalState: "unknown", flowBehavior: "unknown", sensitivities: ["leakage", "heat"], fragility: "low",
      temperatureSensitivity: "medium", usageFrequency: "daily", usageContext: ["home", "gym", "travel"], portionModel: "multiServe", dispensingNeed: ["spray", "other"],
      portability: "high", targetAudience: ["massMarket"], pricePosition: "value", purchaseContext: ["supermarket", "pharmacy", "convenience"], competitionLevel: "saturated",
      shelfImportance: "high", preferredPackagingFamilies: ["spray", "stick", "bottle"], preferredMaterials: ["aluminum", "PP", "carton"],
      positioningTerritories: ["energetic", "modern", "neutral"] }),

  arch("toothpaste", "Dentifrice", "Toothpaste", ["dentifrice", "pate dentifrice", "toothpaste"],
    "Pâte dosée deux fois par jour : tube souple à capsule, étui carton informatif ; codes santé (blanc, bleu).",
    { needsDispensing: "required", needsResealability: "required", needsBarrierProtection: "preferred", needsShelfImpact: "required" },
    { productCategory: "personalCare", productSubcategory: "oralCare", physicalState: "paste", viscosity: "high", flowBehavior: "squeezable", sensitivities: ["contamination", "moisture"],
      fragility: "low", temperatureSensitivity: "low", usageFrequency: "multipleDaily", usageContext: ["home", "travel"], portionModel: "multiServe", dispensingNeed: ["squeeze", "flipCap", "screwCap"],
      portability: "high", targetAudience: ["family", "massMarket"], pricePosition: "value", purchaseContext: ["supermarket", "pharmacy", "convenience"],
      competitionLevel: "saturated", shelfImportance: "high", preferredPackagingFamilies: ["tube", "box"], preferredMaterials: ["composite", "PP", "carton"],
      positioningTerritories: ["clinical", "accessible", "scientific"],
      designSignals: { colorDirection: { primary: ["blanc", "bleu"], reason: "codes santé et hygiène" } } },
    ["Dentifrice blancheur"]),

  // ── Household ──────────────────────────────────────────────────────────────
  arch("bleach", "Eau de javel", "Bleach", ["eau de javel", "javel", "bleach", "chlore"],
    "Liquide corrosif dangereux en cas d'erreur : flacon robuste et étanche, distinct d'une boisson ; pictogrammes et sécurité enfant à sourcer, jamais supposés.",
    { needsLeakProtection: "required", needsLightProtection: "preferred", needsResealability: "required", needsDispensing: "preferred", needsShelfImpact: "preferred", needsVisibility: "notRelevant" },
    { productCategory: "household", productSubcategory: "bleach", physicalState: "liquid", viscosity: "low", flowBehavior: "pourable", sensitivities: ["light", "heat", "leakage"],
      fragility: "low", temperatureSensitivity: "medium", usageFrequency: "occasional", usageContext: ["home", "professional"], portionModel: "multiServe", dispensingNeed: ["pour", "screwCap"],
      portability: "low", targetAudience: ["family", "massMarket", "budget"], pricePosition: "entry", purchaseContext: ["supermarket", "convenience"],
      competitionLevel: "high", shelfImportance: "medium", regulatoryContext: { status: "unknown" }, preferredPackagingFamilies: ["bottle"], preferredMaterials: ["HDPE"],
      positioningTerritories: ["technical", "accessible", "clinical"],
      designSignals: { imageryDirection: { avoid: ["fruits, boissons, enfants"], reason: "ne jamais ressembler à un produit alimentaire" } } }),

  arch("laundryDetergent", "Lessive", "Laundry detergent", ["lessive liquide", "lessive en poudre", "lessive", "detergent", "laundry"],
    "Forme non précisée (poudre ou liquide) : la famille dépend de la forme ; grand format, dosage, poignée.",
    { needsMoistureProtection: "preferred", needsLeakProtection: "preferred", needsDispensing: "preferred", needsResealability: "preferred", needsShelfImpact: "required" },
    { productCategory: "household", productSubcategory: "laundry", physicalState: "unknown", flowBehavior: "unknown", sensitivities: ["moisture", "leakage"], fragility: "low",
      temperatureSensitivity: "low", usageFrequency: "occasional", usageContext: ["home", "professional"], portionModel: "bulk", dispensingNeed: ["pour", "scoop"],
      portability: "low", targetAudience: ["family", "massMarket"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"], competitionLevel: "saturated",
      shelfImportance: "high", preferredPackagingFamilies: ["bottle", "pouch", "box", "bag"], preferredMaterials: ["HDPE", "flexibleFilm", "carton"],
      positioningTerritories: ["bold", "technical", "accessible"] }),

  arch("dishwashing", "Liquide vaisselle", "Dishwashing liquid", ["liquide vaisselle", "produit vaisselle", "dishwashing"],
    "Liquide visqueux utilisé chaque jour, mains mouillées : flacon souple à bouchon doseur.",
    { needsLeakProtection: "required", needsDispensing: "required", needsShelfImpact: "preferred" },
    { productCategory: "household", productSubcategory: "dishwashing", physicalState: "viscous", viscosity: "medium", flowBehavior: "squeezable", sensitivities: ["leakage"], fragility: "low",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "restaurant"], portionModel: "multiServe", dispensingNeed: ["flipCap", "squeeze"],
      portability: "low", targetAudience: ["family", "massMarket"], pricePosition: "value", purchaseContext: ["supermarket", "convenience"], competitionLevel: "high",
      shelfImportance: "medium", preferredPackagingFamilies: ["bottle"], preferredMaterials: ["PET", "HDPE"], positioningTerritories: ["energetic", "accessible"] }),

  // ── Pet care ───────────────────────────────────────────────────────────────
  arch("petFood", "Aliment pour animaux", "Pet food", ["croquettes", "aliment pour chien", "aliment pour chat", "nourriture pour animaux", "pet food"],
    "Granulés secs en gros volume, gras et odorants : sac barrière refermable, poignée ; l'animal en image principale.",
    { needsBarrierProtection: "required", needsMoistureProtection: "required", needsResealability: "preferred", needsShelfImpact: "required", needsStackability: "preferred" },
    { productCategory: "petCare", productSubcategory: "petFood", physicalState: "granules", flowBehavior: "freeFlowing", sensitivities: ["oxygen", "moisture", "oxidation"], fragility: "low",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home"], portionModel: "bulk", dispensingNeed: ["scoop", "pour"], portability: "low",
      targetAudience: ["family", "massMarket"], pricePosition: "mid", purchaseContext: ["supermarket", "specialtyStore", "ecommerce"], competitionLevel: "high",
      shelfImportance: "high", preferredPackagingFamilies: ["bag", "pouch", "box"], preferredMaterials: ["flexibleFilm", "metallizedFilm", "paper"],
      positioningTerritories: ["natural", "playful", "accessible"],
      designSignals: { photographyDirection: { primary: ["animal expressif, regard"], reason: "lien émotionnel avec le maître" } } },
    ["Croquettes premium"]),

  arch("petTreats", "Friandises pour animaux", "Pet treats", ["friandises pour chien", "friandises pour chat", "friandises", "pet treats"],
    "Petites portions données en récompense : sachet refermable, plus ludique que l'aliment principal.",
    { needsResealability: "required", needsMoistureProtection: "preferred", needsBarrierProtection: "preferred", needsShelfImpact: "required" },
    { productCategory: "petCare", productSubcategory: "treats", physicalState: "solid", flowBehavior: "nonFlowing", sensitivities: ["moisture", "oxygen"], fragility: "low",
      temperatureSensitivity: "low", usageFrequency: "daily", usageContext: ["home", "outdoor"], portionModel: "multiServe", dispensingNeed: ["none"], portability: "medium",
      targetAudience: ["family"], pricePosition: "mid", purchaseContext: ["supermarket", "specialtyStore", "ecommerce"], competitionLevel: "medium", shelfImportance: "high",
      preferredPackagingFamilies: ["pouch", "bag", "tub"], preferredMaterials: ["flexibleFilm", "PP"], positioningTerritories: ["playful", "natural"] }),

  // ── Luxury gifting ─────────────────────────────────────────────────────────
  arch("premiumGift", "Coffret cadeau premium", "Premium gift box", ["coffret cadeau", "coffret prestige", "coffret", "gift box", "ecrin"],
    "L'emballage est une partie du cadeau : coffret rigide, ouverture mise en scène, calage ; le contenu peut varier.",
    { needsPremiumPresentation: "required", needsShippingProtection: "preferred", needsShelfImpact: "preferred" },
    { productCategory: "luxury", productSubcategory: "premiumGiftProduct", physicalState: "unknown", fragility: "unknown", usageFrequency: "occasional", usageContext: ["home", "hospitality"],
      portionModel: "unknown", portability: "low", targetAudience: ["premium", "luxury"], pricePosition: "premium", purchaseContext: ["specialtyStore", "ecommerce", "hotel", "directToConsumer"],
      competitionLevel: "medium", shelfImportance: "medium", preferredPackagingFamilies: ["box"], preferredMaterials: ["carton", "paper"],
      positioningTerritories: ["luxury", "elegant", "premium"] },
    ["Coffret prestige"]),
];

/** Deep-freeze: the knowledge base is read-only data. */
function deepFreeze<T>(o: T): T {
  if (o && typeof o === "object" && !Object.isFrozen(o)) {
    Object.freeze(o);
    for (const v of Object.values(o as object)) deepFreeze(v);
  }
  return o;
}

export const PRODUCT_ARCHETYPES: readonly ProductArchetype[] = deepFreeze(RAW);

const BY_ID = new Map(PRODUCT_ARCHETYPES.map((a) => [a.id, a]));
export const archetypeById = (id: string): ProductArchetype | undefined => BY_ID.get(id);
