// Downloads the packaging font library (Google Fonts, SIL OFL / Apache) into
// public/fonts and generates src/styles/fonts.css + src/lib/catalog/fonts.ts.
// Run: node scripts/install-fonts.mjs
import fs from "node:fs/promises";
import path from "node:path";

const FONTS = [
  // [family, category]
  ["Montserrat", "sans"], ["Poppins", "sans"], ["Inter", "sans"], ["Raleway", "sans"],
  ["Work Sans", "sans"], ["DM Sans", "sans"], ["Manrope", "sans"], ["Outfit", "sans"],
  ["Plus Jakarta Sans", "sans"], ["Archivo", "sans"], ["Barlow", "sans"], ["Josefin Sans", "sans"],
  ["Syne", "sans"], ["Space Grotesk", "sans"], ["Urbanist", "sans"], ["Nunito", "sans"],
  ["Lato", "sans"], ["Quicksand", "sans"], ["Oswald", "sans"],
  ["Playfair Display", "serif"], ["Cormorant Garamond", "serif"], ["Libre Baskerville", "serif"],
  ["DM Serif Display", "serif"], ["Lora", "serif"], ["Cinzel", "serif"], ["Bodoni Moda", "serif"],
  ["Fraunces", "serif"], ["Prata", "serif"], ["Marcellus", "serif"], ["EB Garamond", "serif"],
  ["Italiana", "serif"], ["Cormorant", "serif"],
  ["Bebas Neue", "display"], ["Anton", "display"], ["Abril Fatface", "display"], ["Alfa Slab One", "display"],
  ["Righteous", "display"], ["Bungee", "display"], ["Fredoka", "display"], ["Baloo 2", "display"],
  ["Lobster", "display"], ["Shrikhand", "display"], ["Monoton", "display"], ["Staatliches", "display"],
  ["Bagel Fat One", "display"], ["Rubik Mono One", "display"], ["Chewy", "display"],
  ["Pacifico", "script"], ["Dancing Script", "script"], ["Great Vibes", "script"], ["Satisfy", "script"],
  ["Caveat", "script"], ["Allura", "script"], ["Sacramento", "script"], ["Parisienne", "script"],
  ["Space Mono", "mono"], ["IBM Plex Mono", "mono"], ["Courier Prime", "mono"],
];

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1")), "..");
const outDir = path.join(root, "public", "fonts");
await fs.mkdir(outDir, { recursive: true });

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-");

async function css(family) {
  for (const axis of [":wght@400;700", ""]) {
    const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, "+")}${axis}&display=swap`;
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (res.ok) return res.text();
  }
  throw new Error(`No CSS for ${family}`);
}

const faces = [];
const catalog = [];
for (const [family, category] of FONTS) {
  try {
    const text = await css(family);
    // Keep only the "latin" subset blocks (covers French accents).
    const blocks = [...text.matchAll(/\/\* latin \*\/\s*@font-face\s*{([^}]*)}/g)].map((m) => m[1]);
    const weights = [];
    for (const b of blocks) {
      const weight = (b.match(/font-weight:\s*(\d+)/) || [])[1] || "400";
      const style = (b.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
      if (style !== "normal" || weights.includes(weight)) continue;
      const src = (b.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
      if (!src) continue;
      const file = `${slug(family)}-${weight}.woff2`;
      const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
      await fs.writeFile(path.join(outDir, file), buf);
      faces.push(`@font-face {\n  font-family: "${family}";\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url("/fonts/${file}") format("woff2");\n}`);
      weights.push(weight);
    }
    if (weights.length) catalog.push({ id: slug(family), family, category, weights: weights.map(Number) });
    console.log(`✓ ${family} (${weights.join(", ")})`);
  } catch (e) {
    console.log(`✗ ${family}: ${e.message}`);
  }
}

await fs.writeFile(path.join(root, "src", "styles", "fonts.css"), `/* Generated by scripts/install-fonts.mjs — do not edit. */\n\n${faces.join("\n\n")}\n`);
await fs.writeFile(
  path.join(root, "src", "lib", "catalog", "fonts.ts"),
  `// Generated by scripts/install-fonts.mjs — do not edit.\n\nexport type FontCategory = "sans" | "serif" | "display" | "script" | "mono";\n\nexport interface PackagingFont {\n  id: string;\n  family: string;\n  category: FontCategory;\n  weights: number[];\n}\n\nexport const PACKAGING_FONTS: PackagingFont[] = ${JSON.stringify(catalog, null, 2)};\n`
);
console.log(`\n${catalog.length} polices installées.`);
