// Generated by scripts/install-fonts.mjs — do not edit.

export type FontCategory = "sans" | "serif" | "display" | "script" | "mono";

export interface PackagingFont {
  id: string;
  family: string;
  category: FontCategory;
  weights: number[];
}

export const PACKAGING_FONTS: PackagingFont[] = [
  {
    "id": "montserrat",
    "family": "Montserrat",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "poppins",
    "family": "Poppins",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "inter",
    "family": "Inter",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "raleway",
    "family": "Raleway",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "work-sans",
    "family": "Work Sans",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "dm-sans",
    "family": "DM Sans",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "manrope",
    "family": "Manrope",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "outfit",
    "family": "Outfit",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "plus-jakarta-sans",
    "family": "Plus Jakarta Sans",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "archivo",
    "family": "Archivo",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "barlow",
    "family": "Barlow",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "josefin-sans",
    "family": "Josefin Sans",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "syne",
    "family": "Syne",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "space-grotesk",
    "family": "Space Grotesk",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "urbanist",
    "family": "Urbanist",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "nunito",
    "family": "Nunito",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "lato",
    "family": "Lato",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "quicksand",
    "family": "Quicksand",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "oswald",
    "family": "Oswald",
    "category": "sans",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "playfair-display",
    "family": "Playfair Display",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "cormorant-garamond",
    "family": "Cormorant Garamond",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "libre-baskerville",
    "family": "Libre Baskerville",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "dm-serif-display",
    "family": "DM Serif Display",
    "category": "serif",
    "weights": [
      400
    ]
  },
  {
    "id": "lora",
    "family": "Lora",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "cinzel",
    "family": "Cinzel",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "bodoni-moda",
    "family": "Bodoni Moda",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "fraunces",
    "family": "Fraunces",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "prata",
    "family": "Prata",
    "category": "serif",
    "weights": [
      400
    ]
  },
  {
    "id": "marcellus",
    "family": "Marcellus",
    "category": "serif",
    "weights": [
      400
    ]
  },
  {
    "id": "eb-garamond",
    "family": "EB Garamond",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "italiana",
    "family": "Italiana",
    "category": "serif",
    "weights": [
      400
    ]
  },
  {
    "id": "cormorant",
    "family": "Cormorant",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "bebas-neue",
    "family": "Bebas Neue",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "anton",
    "family": "Anton",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "abril-fatface",
    "family": "Abril Fatface",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "alfa-slab-one",
    "family": "Alfa Slab One",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "righteous",
    "family": "Righteous",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "bungee",
    "family": "Bungee",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "fredoka",
    "family": "Fredoka",
    "category": "display",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "baloo-2",
    "family": "Baloo 2",
    "category": "display",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "lobster",
    "family": "Lobster",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "shrikhand",
    "family": "Shrikhand",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "monoton",
    "family": "Monoton",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "staatliches",
    "family": "Staatliches",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "bagel-fat-one",
    "family": "Bagel Fat One",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "rubik-mono-one",
    "family": "Rubik Mono One",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "chewy",
    "family": "Chewy",
    "category": "display",
    "weights": [
      400
    ]
  },
  {
    "id": "pacifico",
    "family": "Pacifico",
    "category": "script",
    "weights": [
      400
    ]
  },
  {
    "id": "dancing-script",
    "family": "Dancing Script",
    "category": "script",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "great-vibes",
    "family": "Great Vibes",
    "category": "script",
    "weights": [
      400
    ]
  },
  {
    "id": "satisfy",
    "family": "Satisfy",
    "category": "script",
    "weights": [
      400
    ]
  },
  {
    "id": "caveat",
    "family": "Caveat",
    "category": "script",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "allura",
    "family": "Allura",
    "category": "script",
    "weights": [
      400
    ]
  },
  {
    "id": "sacramento",
    "family": "Sacramento",
    "category": "script",
    "weights": [
      400
    ]
  },
  {
    "id": "parisienne",
    "family": "Parisienne",
    "category": "script",
    "weights": [
      400
    ]
  },
  {
    "id": "space-mono",
    "family": "Space Mono",
    "category": "mono",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "ibm-plex-mono",
    "family": "IBM Plex Mono",
    "category": "mono",
    "weights": [
      400,
      700
    ]
  },
  {
    "id": "courier-prime",
    "family": "Courier Prime",
    "category": "mono",
    "weights": [
      400,
      700
    ]
  }
];
