import type { VisualStylePreset } from "@/components/workspace/Modals";

// Original 10 Edify presets (data only, safe to import on the server).
export const ALL_VISUAL_STYLES: VisualStylePreset[] = [
  {
    id: "botanical-natural",
    name: "Botanique & Naturel",
    subtitle: "Palette terreuse, sérigraphie organique",
    description: "Tons sauge apaisants, rose poudré délicat et touches florales. Idéal pour les cosmétiques bio et soins holistiques.",
    badge: "✦",
    primaryColor: "#ec4899",
    accentColor: "#059669",
    palette: ["#fdf2f8", "#ec4899", "#059669", "#d97706"],
    bgGradient: "from-rose-50/50 via-white to-emerald-50/40",
    fontFamily: "sans",
    finishing: "Vernis sélectif + Dorure or",
    category: "eco",
  },
  {
    id: "luxury-obsidian-gold",
    name: "Luxe Minimaliste Noir & Or",
    subtitle: "Noir profond et dorure or à chaud 24K",
    description: "Élégance intemporelle pour parfumerie de créateur, haute horlogerie et spiritueux d'exception.",
    badge: "★",
    primaryColor: "#0f172a",
    accentColor: "#f59e0b",
    palette: ["#0f172a", "#1e293b", "#f59e0b", "#fde68a"],
    bgGradient: "from-slate-900 via-slate-950 to-neutral-900",
    fontFamily: "sans",
    finishing: "Dorure or 24K + Soft Touch",
    category: "luxury",
  },
  {
    id: "artisanal-kraft-cafe",
    name: "Café & Kraft Terroir",
    subtitle: "Texture fibreuse, typographie vintage",
    description: "Aspect brut et authentique avec encre noire végétale et tampons de torréfaction artisanale.",
    badge: "☕",
    primaryColor: "#78350f",
    accentColor: "#b45309",
    palette: ["#fef3c7", "#d97706", "#b45309", "#78350f"],
    bgGradient: "from-amber-100/60 via-amber-50 to-orange-100/40",
    fontFamily: "sans",
    finishing: "Embossage relief + Papier recyclé",
    category: "eco",
  },
  {
    id: "cyber-neon-modern",
    name: "Cyber Éclat Holographique",
    subtitle: "Reflets irisés et typographie néo-grotesque",
    description: "Inspiré du design digital moderne, boissons nootropiques, tech et compléments fonctionnels.",
    badge: "⚡",
    primaryColor: "#8b5cf6",
    accentColor: "#06b6d4",
    palette: ["#f3e8ff", "#8b5cf6", "#06b6d4", "#ec4899"],
    bgGradient: "from-violet-50/60 via-white to-cyan-50/50",
    fontFamily: "sans",
    finishing: "Film holographique arc-en-ciel",
    category: "modern",
  },
  {
    id: "clinical-purity-white",
    name: "Soin Clinique & Pureté Médicale",
    subtitle: "Minimalisme dermatologique immaculé",
    description: "Grille suisse rigoureuse, blancheur totale immaculée et repères de dosage cobalt ultra-lisibles.",
    badge: "✚",
    primaryColor: "#2563eb",
    accentColor: "#10b981",
    palette: ["#ffffff", "#f8fafc", "#2563eb", "#10b981"],
    bgGradient: "from-sky-50/50 via-white to-slate-50",
    fontFamily: "sans",
    finishing: "Pelliculage mat antibactérien",
    category: "wellness",
  },
  {
    id: "pastel-scandi-zen",
    name: "Pastel Douceur Scandinave",
    subtitle: "Pêche poudrée, crème vanille & sérénité",
    description: "Teintes réconfortantes, lignes géométriques minimalistes et toucher soyeux ultra-apaisant.",
    badge: "☁",
    primaryColor: "#f43f5e",
    accentColor: "#fb923c",
    palette: ["#fff1f2", "#fed7aa", "#fbcfe8", "#f43f5e"],
    bgGradient: "from-rose-50/70 via-orange-50/40 to-white",
    fontFamily: "sans",
    finishing: "Toucher peau de pêche Soft Velvet",
    category: "wellness",
  },
  {
    id: "retro-apothecary-1920",
    name: "Apothicaire Rétro 1920",
    subtitle: "Gravures historiques & étiquette ornée",
    description: "Hommage aux herboristeries traditionnelles avec armoiries dorées, bordures victoriennes et cachets d'époque.",
    badge: "⚜",
    primaryColor: "#831843",
    accentColor: "#d97706",
    palette: ["#fdf2f8", "#831843", "#d97706", "#1c1917"],
    bgGradient: "from-stone-100 via-amber-50/50 to-stone-200",
    fontFamily: "sans",
    finishing: "Gaufrage relief + Dorure cuivrée",
    category: "vintage",
  },
  {
    id: "pop-art-vibrant",
    name: "Pop Art & Vibrance Énergique",
    subtitle: "Couleurs saturées & motifs géométriques",
    description: "Design jeune et survitaminé avec contrastes audacieux et typographie extra-bold percutante.",
    badge: "✹",
    primaryColor: "#e11d48",
    accentColor: "#facc15",
    palette: ["#fef08a", "#e11d48", "#3b82f6", "#10b981"],
    bgGradient: "from-amber-50 via-rose-50 to-blue-50",
    fontFamily: "sans",
    finishing: "Vernis brillant ultra-gloss",
    category: "modern",
  },
  {
    id: "japanese-wabi-sabi",
    name: "Japonais Wabi-Sabi & Épuré",
    subtitle: "Papier washi texturé & minimalisme zen",
    description: "Éloge de la simplicité et des matières nobles, typographie délicate et espace négatif maîtrisé.",
    badge: "侘",
    primaryColor: "#334155",
    accentColor: "#a8a29e",
    palette: ["#fafaf9", "#e7e5e4", "#78716c", "#292524"],
    bgGradient: "from-stone-50 via-white to-stone-100",
    fontFamily: "sans",
    finishing: "Papier d'art vergé non couché",
    category: "eco",
  },
  {
    id: "high-tech-matte-titanium",
    name: "High-Tech Mat & Titane Chrome",
    subtitle: "Finition soft-touch & accents métalliques",
    description: "Univers premium contemporain avec noir anthracite, reflets aluminium brossé et gravure laser.",
    badge: "◈",
    primaryColor: "#475569",
    accentColor: "#0284c7",
    palette: ["#0f172a", "#334155", "#64748b", "#38bdf8"],
    bgGradient: "from-slate-800 via-slate-900 to-zinc-900",
    fontFamily: "sans",
    finishing: "Vernis sélectif 3D + Foil argent",
    category: "luxury",
  },
];

