import type { ShapeCategory, ShapeModel } from "@/components/workspace/Modals";

// ─── Categories (Pacdora-like families) ──────────────────────────────────────

export const SHAPE_CATEGORIES: { id: ShapeCategory | "all"; label: string }[] = [
  { id: "all",        label: "Tous" },
  { id: "boxes",      label: "Boîtes" },
  { id: "bottles",    label: "Bouteilles & flacons" },
  { id: "jars",       label: "Pots" },
  { id: "pouches",    label: "Sachets & pochettes" },
  { id: "tubes_cans", label: "Tubes" },
  { id: "cans",       label: "Canettes" },
  { id: "tins",       label: "Boîtes métal" },
  { id: "food",       label: "Alimentaire" },
];

// [id, name, category, model, L, W, H (mm), material, keywords]
export type ShapeRow = [string, string, ShapeCategory, ShapeModel, number, number, number, string, string];

export const SHAPE_ROWS: ShapeRow[] = [
  // ── Boîtes ──
  ["folding-box-standard", "Boîte pliante", "boxes", "box", 38, 38, 112, "Carton couché 350g", "étui cosmétique pharmacie reverse tuck"],
  ["tuck-end-box-wide", "Étui large", "boxes", "box", 90, 40, 130, "Carton couché 350g", "étui boîte pliante"],
  ["tuck-end-box-tall", "Étui haut parfum", "boxes", "box", 55, 55, 160, "Carton couché 400g", "parfum étui"],
  ["cube-box", "Boîte cube", "boxes", "box", 80, 80, 80, "Carton couché 350g", "carré cadeau"],
  ["flat-box", "Boîte plate", "boxes", "box", 150, 110, 30, "Carton couché 350g", "plate chocolat thé"],
  ["cereal-box", "Boîte céréales", "boxes", "box", 190, 65, 280, "Carton compact 400g", "céréales petit-déjeuner"],
  ["tea-box", "Boîte à thé", "boxes", "box", 70, 70, 130, "Carton couché 350g", "thé infusion"],
  ["cigarette-box", "Étui à rabat", "boxes", "box", 55, 22, 88, "Carton couché 300g", "petit étui"],
  ["soap-box", "Boîte savon", "boxes", "box", 90, 60, 35, "Kraft 350g", "savon solide"],
  ["candle-box", "Boîte bougie", "boxes", "box", 90, 90, 100, "Carton couché 350g", "bougie cadeau"],
  ["luxury-rigid-box", "Coffret rigide", "boxes", "rigid", 120, 120, 70, "Carton rigide 1,5 mm", "coffret luxe couvercle cloche"],
  ["rigid-watch-box", "Coffret montre", "boxes", "rigid", 100, 100, 80, "Carton rigide 2 mm", "bijou montre luxe"],
  ["rigid-shoe-box", "Boîte à chaussures", "boxes", "rigid", 330, 200, 120, "Carton rigide 1,5 mm", "chaussures"],
  ["gift-box-large", "Grand coffret cadeau", "boxes", "rigid", 300, 220, 100, "Carton rigide 2 mm", "cadeau coffret"],
  ["ecom-mailer", "Boîte postale", "boxes", "mailer", 220, 160, 60, "Carton ondulé E", "e-commerce envoi fefco"],
  ["mailer-small", "Petite boîte postale", "boxes", "mailer", 150, 110, 50, "Carton ondulé E", "e-commerce envoi"],
  ["mailer-large", "Grande boîte postale", "boxes", "mailer", 350, 250, 100, "Carton ondulé B", "e-commerce envoi"],
  ["subscription-box", "Box abonnement", "boxes", "mailer", 280, 200, 90, "Carton ondulé E", "abonnement box"],
  ["shipping-box", "Carton d'expédition", "boxes", "box", 300, 200, 200, "Carton ondulé double", "expédition transport"],
  ["pillow-box", "Boîte berlingot", "boxes", "pillow", 120, 30, 80, "Carton couché 350g", "pillow cadeau"],
  ["display-box", "Présentoir comptoir", "boxes", "display", 200, 150, 80, "Carton ondulé E", "présentoir display"],
  ["sleeve-box", "Boîte à tiroir", "boxes", "box", 110, 80, 30, "Carton couché 400g", "tiroir sleeve"],
  ["pizza-box", "Boîte à pizza", "food", "pizza", 330, 330, 40, "Carton ondulé", "pizza livraison"],
  ["cake-box", "Boîte pâtisserie", "food", "box", 200, 200, 120, "Carton alimentaire", "gâteau pâtisserie"],
  ["burger-box", "Boîte burger", "food", "clamshell", 120, 120, 80, "Carton alimentaire", "burger fast-food clamshell"],
  ["macaron-box", "Boîte macarons", "food", "box", 160, 50, 50, "Carton couché 350g", "macaron confiserie"],
  ["chocolate-box", "Ballotin chocolat", "food", "box", 120, 80, 50, "Carton couché 350g", "chocolat ballotin"],
  ["noodle-box", "Boîte à nouilles", "food", "cup", 90, 90, 100, "Carton alimentaire", "nouilles asiatique take-away"],
  ["fries-box", "Cornet de frites", "food", "cup", 90, 50, 110, "Carton alimentaire", "frites"],
  ["food-tray", "Barquette", "food", "tray", 180, 120, 40, "Carton alimentaire", "barquette plat"],
  ["egg-carton", "Boîte à œufs", "food", "moulded", 150, 100, 70, "Carton moulé", "œufs"],
  ["milk-carton", "Brique de lait", "food", "carton", 70, 70, 190, "Carton aseptique", "lait jus brique"],
  ["juice-carton-small", "Brique de jus", "food", "carton", 60, 40, 105, "Carton aseptique", "jus enfant"],
  ["gable-top-1l", "Brique 1 L", "food", "carton", 70, 70, 240, "Carton aseptique", "lait jus 1 litre"],

  // ── Bouteilles & flacons ──
  ["dropper-bottle", "Flacon pipette", "bottles", "dropper", 34, 34, 95, "Verre ambré", "sérum huile compte-gouttes"],
  ["dropper-bottle-clear", "Flacon pipette transparent", "bottles", "dropper", 34, 34, 95, "Verre transparent", "sérum huile"],
  ["pump-bottle", "Flacon pompe", "bottles", "pump", 55, 55, 170, "PET recyclé", "lotion savon liquide"],
  ["pump-bottle-small", "Petit flacon pompe", "bottles", "pump", 40, 40, 120, "PET recyclé", "crème lotion"],
  ["spray-bottle", "Vaporisateur", "bottles", "spray", 45, 45, 150, "Verre transparent", "brume parfum spray"],
  ["perfume-bottle", "Flacon parfum", "bottles", "spray", 60, 35, 110, "Verre épais", "parfum eau de toilette"],
  ["shampoo-bottle", "Bouteille shampoing", "bottles", "bottle", 60, 40, 200, "PEHD", "shampoing gel douche"],
  ["water-bottle", "Bouteille d'eau", "bottles", "bottle", 65, 65, 220, "PET", "eau boisson"],
  ["juice-bottle", "Bouteille de jus", "bottles", "bottle", 60, 60, 190, "Verre transparent", "jus smoothie"],
  ["soda-bottle", "Bouteille soda", "bottles", "bottle", 70, 70, 240, "PET", "soda boisson"],
  ["beer-bottle", "Bouteille de bière", "bottles", "wine", 60, 60, 230, "Verre ambré", "bière brasserie"],
  ["wine-bottle", "Bouteille de vin", "bottles", "wine", 75, 75, 300, "Verre teinté", "vin bordelaise"],
  ["champagne-bottle", "Bouteille champagne", "bottles", "wine", 90, 90, 300, "Verre épais", "champagne crémant"],
  ["spirits-bottle", "Bouteille spiritueux", "bottles", "bottle", 85, 85, 260, "Verre extra-blanc", "gin rhum whisky"],
  ["olive-oil-bottle", "Bouteille d'huile", "bottles", "wine", 60, 60, 280, "Verre teinté", "huile d'olive"],
  ["sauce-bottle", "Bouteille de sauce", "bottles", "bottle", 55, 55, 180, "Verre transparent", "ketchup sauce"],
  ["syrup-bottle", "Bouteille de sirop", "bottles", "bottle", 75, 75, 250, "Verre transparent", "sirop"],
  ["milk-bottle", "Bouteille de lait", "bottles", "bottle", 75, 75, 210, "Verre transparent", "lait"],
  ["sport-bottle", "Gourde", "bottles", "bottle", 70, 70, 240, "Aluminium", "gourde sport"],
  ["supplement-bottle", "Pilulier", "bottles", "jar", 60, 60, 110, "PEHD blanc", "compléments gélules vitamines"],
  ["jug-bottle", "Bidon", "bottles", "jug", 150, 80, 250, "PEHD", "bidon lessive huile moteur"],
  ["detergent-bottle", "Flacon lessive", "bottles", "jug", 110, 70, 260, "PEHD", "lessive détergent"],
  ["nail-polish", "Flacon vernis", "bottles", "bottle", 30, 30, 70, "Verre épais", "vernis ongles"],

  // ── Pots ──
  ["cosmetic-jar", "Pot crème", "jars", "jar", 65, 65, 50, "Verre dépoli", "crème baume"],
  ["cosmetic-jar-tall", "Pot haut", "jars", "jar", 60, 60, 80, "Verre transparent", "gommage"],
  ["honey-jar", "Pot de miel", "jars", "jar", 75, 75, 95, "Verre transparent", "miel confiture"],
  ["jam-jar", "Pot de confiture", "jars", "jar", 70, 70, 85, "Verre transparent", "confiture"],
  ["mason-jar", "Bocal", "jars", "jar", 85, 85, 130, "Verre transparent", "bocal conserve"],
  ["candle-jar", "Pot à bougie", "jars", "jar", 80, 80, 90, "Verre ambré", "bougie parfumée"],
  ["baby-food-jar", "Petit pot bébé", "jars", "jar", 60, 60, 65, "Verre transparent", "bébé"],
  ["protein-tub", "Pot de protéine", "jars", "tub", 120, 120, 170, "PEHD", "protéine whey"],
  ["yogurt-cup", "Pot de yaourt", "jars", "tub", 70, 70, 75, "PP", "yaourt dessert"],
  ["ice-cream-tub", "Pot de glace", "jars", "papertub", 100, 100, 90, "Carton alimentaire", "glace crème glacée"],
  ["deli-container", "Boîte traiteur", "jars", "tub", 115, 115, 70, "PP transparent", "traiteur salade"],

  // ── Sachets & pochettes ──
  ["stand-up-pouch", "Doypack", "pouches", "pouch", 140, 80, 210, "Kraft + PE", "doypack zip café"],
  ["stand-up-pouch-small", "Petit doypack", "pouches", "pouch", 100, 60, 150, "Film métallisé", "doypack snack"],
  ["coffee-pouch", "Sachet café valve", "pouches", "pouch", 130, 80, 220, "Kraft + alu", "café grain valve"],
  ["flat-pouch", "Sachet plat", "pouches", "flatpouch", 120, 10, 170, "Film métallisé", "sachet plat"],
  ["chips-bag", "Paquet de chips", "pouches", "flatpouch", 200, 20, 280, "Film métallisé", "chips snack"],
  ["candy-bag", "Sachet bonbons", "pouches", "flatpouch", 150, 15, 200, "Film transparent", "bonbons confiserie"],
  ["sachet-sample", "Échantillon", "pouches", "sachet", 60, 5, 80, "Film alu", "échantillon dosette"],
  ["stick-pack", "Stick", "pouches", "sachet", 25, 5, 110, "Film alu", "stick sucre poudre"],
  ["tea-sachet", "Sachet de thé", "pouches", "sachet", 70, 5, 90, "Papier", "thé infusion"],
  ["face-mask-sachet", "Sachet masque", "pouches", "sachet", 130, 5, 180, "Film alu", "masque tissu"],
  ["pet-food-bag", "Sac croquettes", "pouches", "bag", 250, 100, 400, "Film PE", "croquettes animaux"],
  ["flour-bag", "Sac de farine", "pouches", "paperbag", 150, 80, 250, "Papier kraft", "farine sucre"],
  ["coffee-bag-gusset", "Sac café soufflet", "pouches", "bag", 110, 70, 250, "Kraft + alu", "café soufflet"],
  ["rice-bag", "Sac de riz", "pouches", "bag", 200, 90, 330, "Film PE", "riz céréales"],


  // ── Tubes ──
  ["squeeze-tube", "Tube souple", "tubes_cans", "tube", 35, 35, 150, "PE", "crème dentifrice"],
  ["squeeze-tube-large", "Grand tube", "tubes_cans", "tube", 50, 50, 190, "PE", "gel douche crème"],
  ["lip-balm-tube", "Stick à lèvres", "tubes_cans", "papertube", 18, 18, 70, "Carton", "baume lèvres"],
  ["cylinder-tube", "Tube carton", "tubes_cans", "papertube", 70, 70, 180, "Carton kraft", "tube cylindrique cadeau"],
  ["poster-tube", "Tube poster", "tubes_cans", "papertube", 60, 60, 420, "Carton kraft", "affiche envoi"],
  ["deodorant-stick", "Stick déodorant", "tubes_cans", "papertube", 45, 45, 110, "Carton", "déodorant solide"],

  // ── Canettes ──
  ["beverage-can", "Canette 330 ml", "cans", "can", 66, 66, 115, "Aluminium", "soda bière boisson"],
  ["sleek-can", "Canette slim 250 ml", "cans", "can", 53, 53, 134, "Aluminium", "energy drink"],
  ["tall-can", "Canette 500 ml", "cans", "can", 66, 66, 168, "Aluminium", "bière"],
  ["food-can", "Boîte de conserve", "cans", "tin", 73, 73, 110, "Fer blanc", "conserve"],
  ["aerosol-can", "Aérosol", "cans", "spray", 50, 50, 190, "Aluminium", "spray déodorant"],

  // ── Boîtes métal ──
  ["round-tin", "Boîte ronde métal", "tins", "tin", 90, 90, 60, "Fer blanc", "bonbons baume"],
  ["tea-tin", "Boîte à thé métal", "tins", "tin", 75, 75, 120, "Fer blanc", "thé"],
  ["cookie-tin", "Boîte à biscuits", "tins", "tin", 200, 200, 80, "Fer blanc", "biscuits cadeau"],
  ["mint-tin", "Boîte à pastilles", "tins", "tin", 60, 60, 20, "Fer blanc", "pastilles"],

  // ── Produits d'Afrique centrale et de l'Ouest (contenants réellement utilisés) ──
  ["juice-bottle-30cl", "Petite bouteille de jus 30 cl", "bottles", "bottle", 58, 58, 165, "PET transparent", "bissap gingembre folere jus local baobab"],
  ["glass-juice-25cl", "Bouteille verre 25 cl", "bottles", "bottle", 55, 55, 170, "Verre transparent", "jus bissap artisanal limonade"],
  ["oil-bottle-1l", "Bouteille d'huile 1 L", "bottles", "bottle", 82, 82, 290, "PET transparent", "huile palme arachide soja raffinée"],
  ["jerrican-5l", "Bidon 5 L", "bottles", "jug", 190, 120, 300, "PEHD", "bidon huile palme vin miel vrac jerrican"],
  ["big-beer-bottle", "Grande bouteille 65 cl", "bottles", "wine", 72, 72, 290, "Verre ambré", "bière 65 cl boisson gazeuse"],
  ["drink-yogurt-bottle", "Bouteille de yaourt à boire", "bottles", "bottle", 55, 55, 150, "PEHD blanc", "yaourt à boire lait caillé kossam"],
  ["cosmetic-oil-bottle", "Flacon huile 100 ml", "bottles", "bottle", 42, 42, 140, "PET ambré", "huile coco ricin cheveux huile corps"],
  ["roll-on-bottle", "Roll-on parfum", "bottles", "bottle", 22, 22, 85, "Verre transparent", "huile parfumée musc roll-on"],
  ["hot-sauce-bottle", "Flacon de piment", "bottles", "bottle", 45, 45, 150, "Verre transparent", "piment sauce pimentée huile pimentée"],
  ["water-sachet", "Sachet d'eau 50 cl", "pouches", "sachet", 150, 5, 210, "Film PE", "eau sachet pure water"],
  ["gari-bag", "Sac de gari / farine", "pouches", "bag", 180, 70, 280, "Film PE", "gari tapioca couscous manioc farine de maïs"],
  ["spice-sachet", "Sachet d'épices", "pouches", "flatpouch", 90, 8, 140, "Film métallisé", "épices poivre blanc mélange soya condiments"],
  ["plantain-chips-bag", "Sachet chips plantain", "pouches", "flatpouch", 160, 15, 230, "Film métallisé", "chips plantain banane manioc"],
  ["peanut-butter-jar", "Pot de pâte d'arachide", "jars", "jar", 80, 80, 100, "PET transparent", "pâte d'arachide beurre de cacahuète"],
  ["spice-jar", "Pot à épices", "jars", "jar", 48, 48, 100, "Verre transparent", "poivre de Penja piment épices"],
  ["shea-butter-jar", "Pot de karité", "jars", "jar", 75, 75, 55, "PP blanc", "beurre de karité baume pommade"],
  ["hair-cream-tub", "Pot de crème capillaire", "jars", "tub", 90, 90, 70, "PP", "crème capillaire défrisant pommade cheveux"],
  ["tomato-paste-tin", "Boîte de tomate concentrée", "cans", "tin", 60, 60, 45, "Fer blanc", "tomate concentrée double concentré"],
  ["milk-powder-tin", "Boîte de lait en poudre", "tins", "tin", 100, 100, 130, "Fer blanc", "lait en poudre bébé nido"],
  ["bouillon-box", "Étui de cubes d'assaisonnement", "boxes", "box", 60, 30, 50, "Carton couché 300g", "cube bouillon assaisonnement"],
  ["soap-wrap", "Savon emballé", "boxes", "box", 85, 28, 55, "Papier kraft", "savon noir savon de toilette savon artisanal"],
  ["chocolate-bar", "Tablette de chocolat", "food", "box", 80, 12, 160, "Carton couché 300g", "tablette chocolat cacao"],

];

